### ISSUE TITLE
No task registered for key name1

### ISSUE THREAD

**Issue by mx-kshitij** [Rapsssito/react-native-background-actions#101]
```
08-20 11:13:13.792 20174 23701 D ReactNativeJS: Trying to start background service
08-20 11:13:13.842   866   876 E statsd  : Predicate 5980654721335871649 dropping data for dimension key (10)0x2010101->10553[I] (10)0x30000->com.facebook.react.HeadlessJsTaskService[S] 
08-20 11:13:13.844 20174 23701 W ReactNativeJS: No task registered for key name1
08-20 11:13:13.852   866   876 E statsd  : Predicate 5980654721335871649 dropping data for dimension key (10)0x2010101->10553[I] (10)0x30000->com.facebook.react.HeadlessJsTaskService[S] 
08-20 11:13:13.866  1695  1788 E QMI_FW  : qmi_cci_get_ref: ref count increased 2
08-20 11:13:13.866  1695  1739 E QMI_FW  : qmi_cci_get_ref: ref count increased 2
```

On calling the BackgroundJob.start()

**Comment by Rapsssito** [comment]
@mx-kshitij, I am sorry for your issue. Could you provide a minimal reproducible example code?

**Comment by mx-kshitij** [comment]
`import { Platform, Linking } from 'react-native';
import BackgroundJob from 'react-native-background-actions';

export async function JA_BackgroundAction(taskName, taskTitle, taskDesc, linkingURI, runOnce, repeatInterval, stopOnExit, action, notificationColor) {

	BackgroundJob.on('expiration', () => {
		console.log('iOS: I am being closed!');
	});


	console.log('Setting time');

	sleep = (time) => new Promise((resolve) => setTimeout(() => resolve(), time));


	taskRunOnce = async () => {
		console.log('Reached function');
		if (Platform.OS === 'ios') {
			console.warn(
				'This task will not keep your app alive in the background by itself, use other library like react-native-track-player that use audio,',
				'geolocalization, etc. to keep your app alive in the background while you excute the JS from this library.'
			);
		}
		await new Promise(async (_resolve) => {

			// running my action
		});
	};

	taskRepeat = async (taskData) => {
		console.log('Reached function');
		if (Platform.OS === 'ios') {
			console.warn(
				'This task will not keep your app alive in the background by itself, use other library like react-native-track-player that use audio,',
				'geolocalization, etc. to keep your app alive in the background while you excute the JS from this library.'
			);
		}
		await new Promise(async (_resolve) => {
			// For loop with a delay
			const { delay } = taskData;

			for (let i = 0; BackgroundJob.isRunning(); i++) {
			        // running my action
				await sleep(delay);
			}
		});
	};

	var options = {
		taskName: taskName,
		taskTitle: taskTitle,
		taskDesc: taskDesc,
		taskIcon: {
			name: 'ic_launcher',
			type: 'mipmap',
		},
		color: notificationColor,
		linkingURI: linkingURI,
		parameters: {
			delay: 5000,
		},
	};

	function handleOpenURL(evt) {
		console.log(evt.url);
		// do something with the url
	}

	Linking.addEventListener('url', handleOpenURL);

	initiateBackgroundTask = async () => {

		console.log('taskName: ' + options.taskName);
		console.log('taskTitle: ' + options.taskTitle);
		console.log('taskDesc: ' + options.taskDesc);
		console.log('linkingURI: ' + options.linkingURI);
		console.log('color: ' + options.color);

		if (!runOnce) {
			options.parameters.delay = repeatInterval;
		}

		try {
			console.log('Trying to start background service');
			var taskName = options.taskName;

			if (runOnce) {
				await BackgroundJob.start(taskRunOnce, options);
				console.log('Running process with identifier : "' + taskName + '".');
				console.log('Successful start!');
			}
			else {
				if (!BackgroundJob.isRunning()) {
					await BackgroundJob.start(taskRepeat, options);
					console.log('Running process with identifier : "' + taskName + '".');
					console.log('Successful start!');
				}
				else {
					console.log('Start failed. Another process already running.');
				}
			}
		} catch (e) {
			console.log('Error', e);
		}
	};

	stopBackgroundTask = async () => {
		console.log('Stop background service');
		await BackgroundJob.stop();
	};

	console.log('Initiating bg');

	console.log('Initiating task ..');

	initiateBackgroundTask();
}
`

**Comment by mx-kshitij** [comment]
@Rapsssito Hi. Did you get any time to check this out ?

**Comment by Rapsssito** [comment]
@mx-kshitij, I am sorry but not yet. I will come back to you as soon as I have tested your code.

**Comment by mx-kshitij** [comment]
Got it working with some help. Conflicting libraries in node_modules folder
