### ISSUE TITLE
Doesn't work when the app is in background or closed

### ISSUE THREAD

**Issue by erkankarabulut** [Rapsssito/react-native-background-actions#106]
I've tried the toy example on my android phone (API level 30) and the task is not executed when the app is in background or when the app is closed. Can someone confirm if it works for them or not?

**Comment by Rapsssito** [comment]
@erkankarabulut, may this be related to #97 ?

**Comment by GiuseppeEpifani** [comment]
> Probé el ejemplo del juguete en mi teléfono Android (API nivel 30) y la tarea no se ejecuta cuando la aplicación está en segundo plano o cuando la aplicación está cerrada. ¿Alguien puede confirmar si les funciona o no?

same problem, what solution did you do?
