### ISSUE TITLE
How to  implement react-native-track-player ?

### ISSUE THREAD

**Issue by GaylordP** [Rapsssito/react-native-background-actions#110]
Hello :)

Thanks you very much for your library.

You mention in your documentation `react-native-track-player` in order to be able to work correctly on iOS. 

But I can't find an example of an implementation. I read [this issue](https://github.com/Rapsssito/react-native-background-actions/issues/31) correctly but I think it is a bit incomplete. 

I searched the internet a lot (especially in all github looking for the `react-native-track-player` package) without finding an answer.

If I use [your example](https://github.com/Rapsssito/react-native-background-actions/blob/master/examples/backgroundExample/App.js), how would you implement `react-native-track-player` ?

    const taskRandom = async (taskData) => {
      if (Platform.OS === 'ios') {
          console.warn(
              'This task will not keep your app alive in the background by itself, use other library like react-native-track-player that use audio,',
              'geolocalization, etc. to keep your app alive in the background while you excute the JS from this library.'
          );
      }
      await new Promise(async (resolve) => {
          // For loop with a delay
          const { delay } = taskData;
          console.log(BackgroundJob.isRunning(), delay)
          for (let i = 0; BackgroundJob.isRunning(); i++) {
              console.log('Runned -> ', i);
              await BackgroundJob.updateNotification({ taskDesc: 'Runned -> ' + i });
              await sleep(delay);
          }
      });
    };

Thanks you very much and sorry for my bad english, I'm french :)

**Comment by Rapsssito** [comment]
@GaylordP, expanding the example would be:

```js

const taskRandom = async (taskData) => {
  if (Platform.OS === 'ios') {
      console.warn(
          'This task will not keep your app alive in the background by itself, use other library like react-native-track-player that use audio,',
          'geolocalization, etc. to keep your app alive in the background while you excute the JS from this library.'
      );
  }
  
await new Promise((resolve) => {
        // Playing listeners
        const listenerChange = TrackPlayer.addEventListener('playback-state', (newState) => {
            // Do stuff
            if (newState.state === TrackPlayer.STATE_PLAYING) {
                // What to do when the play button is pressed
            } else if (newState.state === TrackPlayer.STATE_PAUSED) {
                // What to do when the pause button is pressed
            }
        });
    });
};
```

**Comment by GaylordP** [comment]
Thanks for your reply :)

I'm sorry (maybe I don't understand because my English is bad) but this example is incomplete right ?

I that adding these few lines in the original code of [this example](https://github.com/Rapsssito/react-native-background-actions/blob/master/examples/backgroundExample/App.js) does make it work, is something missing ? 

Thanks you in adavance

**Comment by Rapsssito** [comment]
@GaylordP, there is a lot more configuration needed for react-native-track-player to work. However, this is outside the scope of this library, you may want to ask this in their repository.
