### ISSUE TITLE
[Android 11] App Crashes after calling BackgroundService.start()

### ISSUE THREAD

**Issue by IvKr95** [Rapsssito/react-native-background-actions#111]
**Specs**

- "react": "16.13.1"
- "react-native": "0.63.4"
- "react-native-background-actions": "^2.6.5"
- Android 11

```js
import BackgroundService from 'react-native-background-actions';
import { scan } from '../ble/peripherals/peripherals';
import { connectToDB, createTable, insertLog } from '../db';
import { getShieldMac } from './localstorage';

const DELAY = 5 * 1000;

const sleep = (time: number) => new Promise(resolve => setTimeout(() => resolve('continue'), time));

const veryIntensiveTask = async () => {
    const data = await getData();
    console.log('g');
    await new Promise(async _ => {
        for (let i = 0; BackgroundService.isRunning(); i++) {
            await sleep(DELAY);

            const result = await scan(nfcShieldMac).catch(error => {
                //TODO: handle error on timeout or device error
                console.log('ERROR SCANNING TARGETED SHIELD =', error);
            });

            if (result) {
                if (data === result.mac) {
                    try {
                        const db = await connectToDB();
                        await createTable(db);
                        await insertLog(db, shield);
                    } catch (e) {
                        console.log('ERROR DB =', e);
                    }
                }
            } else {
                stopBackgroundTask();
            }
        }
    });
};

const options = {
    taskName: 'Example',
    taskTitle: 'ExampleTask title',
    taskDesc: 'ExampleTask description',
    taskIcon: {
        name: 'ic_launcher_foreground',
        type: 'mipmap',
    },
};

export const startBackgroundTask = async () => {
    await BackgroundService.start(veryIntensiveTask, options);
};

export const stopBackgroundTask = async () => {
    await BackgroundService.stop();
};
```

**Comment by Rapsssito** [comment]
@IvKr95, could you please narrow down which part of the code is causing the issue?

**Comment by IvKr95** [comment]
This is the code that is responsible for scanning BLE ad packages and sending them to our backend then if everything is fine we'd like to fire up a background task -> startBackgroundTask(). However, the app crashes for an unknown reason. I also update my AndroidManifest.xml with  
`<service android:name="com.asterinet.react.bgactions.RNBackgroundActionsTask" />`

const associate = async (nfcMac: string) => {
            saveShieldMac(nfcShieldMac);

            const shield = await scan(nfcMac).catch(error => {
                console.log('ERROR SCANNING =', error);
            });

            if (shield) {
                const { mac: bleMac, hardwareVersion, softwareVersion } = shield;

                await sendVersion({
                    mac_address: bleMac,
                    hw_version: hardwareVersion,
                    sw_version: softwareVersion,
                }).catch(error => {
                    console.log('ERROR SENDING VERSION =', error);

                    if (error.response && error.response.status === 404) {
                        throw new Error(INVALID_MAC);
                    }

                    throw new Error(BACKEND_ERROR);
                });

                if (nfcMac === bleMac) {
                    try {
                        const db = await connectToDB();
                        await createTable(db);
                        await insertLog(db, shield);
                    } catch (e) {
                        console.log('ERROR DB =', e);
                    }
                }

                startBackgroundTask(); // <----- here we are starting a background task

                return true;
        }
    };

**Comment by IvKr95** [comment]
I failed to add <uses-permission android:name="android.permission.WAKE_LOCK" /> to my AndroidManifest.xml, after adding it the issue was resolved. But now the app collects data in the foreground just fine, but in the background it works inconsistently.

**Comment by Rapsssito** [comment]
@IvKr95, background tasks are inconsistent because of differences between different OS and the current battery status of the device. That is an expected behavior.
