### ISSUE TITLE
Unable to start service com.asterinet.react.bgactions.RNBackgroundActionsTask@ebe9ce4 with Intent { cmp=com.app/com.asterinet.react.bgactions.RNBackgroundActionsTask (has extras) }: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference

### ISSUE THREAD

**Issue by abolfazlyounesi** [Rapsssito/react-native-background-actions#113]
I am getting this error on production, and it causes crashes for some of the users, any ideas on how to solve this?

`Unable to start service com.asterinet.react.bgactions.RNBackgroundActionsTask@ebe9ce4 with Intent { cmp=com.app/com.asterinet.react.bgactions.RNBackgroundActionsTask (has extras) }: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
`

**Comment by Rapsssito** [comment]
@abolfazlyounesi, could you provide more information, any sort of reproducible code?
