### ISSUE TITLE
How do I hide the notification after the task is done?

### ISSUE THREAD

**Issue by Applizone** [Rapsssito/react-native-background-actions#116]
Currently from the example code, the backgroundjob will be start and inside it having a loop as long as the ```BackgroundJob.isRunning()``` is not null.

```
        for (let i = 0; BackgroundJob.isRunning(); i++) {
            console.log('Runned -> ', i);
            await BackgroundJob.updateNotification({ taskDesc: 'Runned -> ' + i });
            await sleep(delay);
        }
```

inside this loop, I'm planning to retrieve all unsync data from local database and sync it to server and while it download, I can update the notification. And after it finish sync, it will sleep waiting for next delay. And while it sleep, synonym with doing nothing, I want the notification to hide. Is it possible? 

Plus the only way to hide the notification is calling for ```await BackgroundJob.stop();```. Yeah, I just did by clicking Ctrl+F5 on my VSCode and it will start and stop the service. I try to put the stop in the loop, it will hide but it also stop the service.

```
/// HIDE BUT NULL THE OBJECT
        for (let i = 0; BackgroundJob.isRunning(); i++) {
            console.log('Runned -> ', i);
            await BackgroundJob.updateNotification({ taskDesc: 'Runned -> ' + i });
            setTimeout(async () => {
              await BackgroundJob.stop();
            }, 5000);
            await sleep(delay);
        }
```

Does it have any other enhancement something like ```BackgroundJob.hideNotification()``` so I can hide it before sleep.

**Comment by Rapsssito** [comment]
@Applizone I am sorry but this cannot be achieved because of Android UI policies and permissions. This library is oriented for long running background tasks. If you want to run a tasks periodically, other community modules might be more suitable.
