### ISSUE TITLE
How to hide the Notification when app is running in foreground and background mode.

### ISSUE THREAD

**Issue by leonidlewis** [Rapsssito/react-native-background-actions#118]
I am running my app with this module and works well.
I'd like to hide the notification from the notification panel when the app is working without the background job stopping.
Currently, We can hide the notification calling panel backgroundJobs. stop().
Is there a good method to hide the notification?

**Comment by Rapsssito** [comment]
@leonidlewis, the notification cannot be hidden while the background process is running. Once the background process finishes, the notification eventually disappears (it might take a few minutes, it depends on the Android implementation).
