### ISSUE TITLE
[Query, not a bug] How can I store data locally?

### ISSUE THREAD

**Issue by Shaswati** [Rapsssito/react-native-background-actions#122]
I am using this library to collect sensor data in the background. I could successfully collect data even if the application is removed/killed from the background state. 
Now, I want to store that data in local storage first. Once the user gets connected to the server, I will sync data with the server.
What can be the approach to achieve that? Any advice will be appreciable.

**Comment by Rapsssito** [comment]
@Shaswati, for local storage I highly suggest you using https://github.com/react-native-async-storage/async-storage.
