### ISSUE TITLE
Android 12 backgroud service not working when turn off screen

### ISSUE THREAD

**Issue by GiuseppeEpifani** [Rapsssito/react-native-background-actions#125]
Hello, very good library, I wanted you to help me with the following problem, it turns out that when I am debugging my application connected with the usb to my computer, the service always works in the background, even when the screen is off, but when I use the application without my cell phone being connected to the electric current, after 5 minutes since the screen is off, the service stops and is only restored when I unlock the cell phone again.

PS: My application consists of creating a timer that throws alerts every certain interval of time, this service can last up to 48 hours and it is only for android.

PD2: I only managed to make the service work at all times when I disable the energy saving of the application that comes by default as shown in the image below:

![image](https://user-images.githubusercontent.com/52092652/160496173-aec4f791-acb7-46c8-ba39-9defbc4f1553.png)

**Comment by Rapsssito** [comment]
@GiuseppeEpifani, sadly this is out of the scope of this module as the OS decides whether or not to allow a background job to keep running in the background. However, for alerts, I highly recommend using other libraries that setup background timers or intervals.
