### ISSUE TITLE
The service notification disappears after some times

### ISSUE THREAD

**Issue by AlenToma** [Rapsssito/react-native-background-actions#126]
Hi, as the title says, the notification disappears after sometime but the `BackgroundService.isRunning` is still running.

Is that okey ? or is it a problem.

as I know when the notification disappears it should indicate that the service is down right?

**Comment by Rapsssito** [comment]
@AlenToma, the background handling implementation heavily depends on the OS flavor you are running. Normally, if when the notification disappears, it means the service is no longer running, **but it may not be the case**. The only way of knowing is checking the process itself.

**Comment by AlenToma** [comment]
The process is while loop that always running, so if there were an error on the android part. then you could not have seen it.
Now I have downgraded to `2.6.2` and everything works as it should be. 

The notification is always up as long as my app is open.

I am using this in `Samsung s10 lite` with android version 11

**Comment by JariPulkkinen** [comment]
I also noticed that the service got stopped when I closed the application. Call to stopForeground() call here might be the reason:

https://github.com/Rapsssito/react-native-background-actions/blob/318375c7a57507f6266c151255509210f42bf85a/android/src/main/java/com/asterinet/react/bgactions/RNBackgroundActionsTask.java#L92

**Comment by AlenToma** [comment]
Obs I forgot to say that the notification disappear only when the app have gone on foreground for 6 to 10 mins

**Comment by Rapsssito** [comment]
> I also noticed that the service got stopped when I closed the application. May be related. Call to stopForeground() here might be the reason:
> 
> https://github.com/Rapsssito/react-native-background-actions/blob/318375c7a57507f6266c151255509210f42bf85a/android/src/main/java/com/asterinet/react/bgactions/RNBackgroundActionsTask.java#L92

@JariPulkkinen that `this.stopForeground(false);` is only called when there was already a running background task and you started a new one. It should not interfere.

**Comment by Rapsssito** [comment]
@AlenToma, does it happen in version 2.6.4?

**Comment by AlenToma** [comment]
Hmm was `2.6.4` the latest version? if it was then yes.

**Comment by Mhp23** [comment]
@Rapsssito in the latest version (2.6.6) background services will be stop and notification bar will gone when close application, before updating to the latest version it was been working correctly, please review.

**Comment by Rapsssito** [comment]
@Mhp23, did it work in 2.6.5 or 2.6.4 ?

**Comment by Mhp23** [comment]
@Rapsssito in v2.6.5 that I worked by it, it hadn't the problem and work correctly.

**Comment by AnagramEngineering** [comment]
I see the notification disappear as well after 1 min (it looked pretty exaxt) (Pixel3, Android 12). 

(Application is in background, background process is still running (i see the console outputs) also after the notification went away)

my guess was that the system is maybe removing them automatically (as it's pretty exactly one minute until it's gone) but haven#t found anything on this topic. 

i'm using the latest 2.6.6 version.

**Comment by Rapsssito** [comment]
@AnagramEngineering @Mhp23 @AlenToma could you check if this is fixed in the last version as I reverted #124

**Comment by AnagramEngineering** [comment]
I can confirm this is working with 2.6.6 version. The notification is shown until the process is ended (which is happening after 5 minutes on my side (closing ble connection). 

thx @Rapsssito

**Comment by AlenToma** [comment]
I am truly sorry I did not have time to test this with the other version, will try to make time to test it later on.
