### ISSUE TITLE
Documentation should mention about adding BGTaskSchedulerPermittedIdentifiers to info.plist

### ISSUE THREAD

**Issue by juho-ylikyla** [Rapsssito/react-native-background-actions#129]
Firstly, thank you for this super useful library 🙏 

The `INSTALL.MD` document mentions adding the background processing capability. In order to upload an app that has the mentioned capability, `info.plist` needs to have `BGTaskSchedulerPermittedIdentifiers` value set correctly. Otherwise, the upload will error with something like

```
"Missing Info.plist value. The Info.plist key 'BGTaskSchedulerPermittedIdentifiers' must contain a list of identifiers used to submit and handle tasks when 'UIBackgroundModes' has a value of 'processing'. For more information, refer to the Information Property List Key Reference at https://developer.apple.com/library/ios/documentation/General/Reference/InfoPlistKeyReference/Introduction/Introduction.html."
```

I can create a PR to update the documentation if you see that to be useful.

**Comment by Rapsssito** [comment]
@juho-ylikyla, thanks for the feedback! Please, feel free to create a PR!

**Comment by TheSteveHan** [comment]
I've been looking through the code base trying to figure out why we need to background processing capability on ios without much luck. BackgroundService seems to behave the same way(giving ~30s of run time after app goes to background) on ios with/without the capability? Any pointers @Rapsssito
