### ISSUE TITLE
how does this module keeps ios task in background?

### ISSUE THREAD

**Issue by SymntxHomendra51** [Rapsssito/react-native-background-actions#131]
I've seen other libraries which keep tasks in the background but they are limited to minimum 15 minutes of intervals.

-  I've tried this library in android and its works in intervals of 2minutes as I've defined. 
- But I don't know Will It be the same for ios too?. can someone spread some light on it? 
- does this eliminate the 15 minute limit in ios?.

**Comment by Rapsssito** [comment]
Hi @SymntxHomendra51, the documentation says the following:

> iOS: This library relies on iOS's [UIApplication beginBackgroundTaskWithName method](https://developer.apple.com/documentation/uikit/uiapplication/1623051-beginbackgroundtaskwithname?language=objc), which won't keep your app in the background forever by itself. However, you can rely on other libraries like [react-native-track-player](https://github.com/react-native-kit/react-native-track-player) that use audio, geolocalization, etc. to keep your app alive in the background while you execute the JS from this library.
