### ISSUE TITLE
How to run a task when app is in background

### ISSUE THREAD

**Issue by ghorbani-m** [Rapsssito/react-native-background-actions#132]
For this purpose, I used the combination of `react-native-background-action` and `react-native-background-fetch`.
I configured the BackgroundFetch to run every 15 minutes and call a function, inside of the function I tried to start a "BackgroundJob".
Something like this :
```
 if (!BackgroundJob.isRunning())
        await BackgroundJob.start<TaskParams>(backgroundTask, {
          ...defaultOptions,
          parameters: {
            callback: options?.callback,
            assets,
          },
        })
```
But when the app runs in the background I get this error message:
``
[Error: Not allowed to start service Intent { cmp='packgeName'/com.asterinet.react.bgactions.RNBackgroundActionsTask (has extras) }: app is in background uid UidRecord{3090e14 u0a296 TRNB idle change:uncached procs:0 seq(0,0,0)}]
``

**Comment by Rapsssito** [comment]
@ghorbani-m, please, check that you have followed all the steps in: https://github.com/Rapsssito/react-native-background-actions/blob/master/INSTALL.md

**Comment by Rapsssito** [comment]
@ghorbani-m, you are right. You cannot start a "foreground task" while the app is in the background since it is not allowed by Android.

**Comment by pratikSeven** [comment]
Hi,
I noticed there was a recent pull request addressing the issue with starting a foreground task using the library. Has this update provided a working solution for this mentioned issue?
