### ISSUE TITLE
Unhandled JS Exception: Unexpected identifier '_react Native Background Actions' 

### ISSUE THREAD

**Issue by SokolovRU** [Rapsssito/react-native-background-actions#137]
Hello. I put everything according to the instructions, but I ran into an error that I didn't understand. Where should I look?

Unhandled JS Exception: Unexpected identifier '_reactNativeBackgroundActions'

no stack
<img width="356" alt="Снимок экрана 2022-06-29 в 14 26 03" src="https://user-images.githubusercontent.com/105442172/176425760-d41c3eec-fbe8-4d86-8e24-fb54e95ee1de.png">

The project is very confusing, and I have never worked with this library

**Comment by roman-march** [comment]
I have the same error

**Comment by SokolovRU** [comment]
Okay Most likely it's just a mistake that I didn't use this library correctly.

To work, I created a class that has a start and stop method.

And when I need to call work, I just access the object of this class and call the desired method.

I'll just close it. For everyone who has such a thing, try to do it through the class.
