### ISSUE TITLE
It is not executing all the line which is mention in BackgroundService.start.

### ISSUE THREAD

**Issue by Pranavpatel428** [Rapsssito/react-native-background-actions#139]
Hi Guys,
I am a trying to execute code in a screen after I run navigation.goBack(), it was working completely fine for a couple of releases but now it suddenly stopped executing the code after the navigation.goBack(). It is supposed to work something like this:

let personalPostTask = async () => {
    navigation.goBack();

    await createPost({
      variables: {
        postContent: {
          media: mediaFileArray,
          body: postText,
          privacy: postStatus,
        },
        tags: {
          userTags: TempList,
        },
      },
    });
    //From this line it is not executing.
    dispatchUserState({
      type: UserAction.Update,
    });
    Toast.showWithGravity(
      "Personal Post Uploaded Successfully !",
      Toast.SHORT,
      Toast.BOTTOM
    );
  };

**Comment by Rapsssito** [comment]
@Pranavpatel428, I am sorry, but you cannot access the UI from the background tasks.
