### ISSUE TITLE
'_reactNativeBackgroundActions.default.isRunning' is undefined

### ISSUE THREAD

**Issue by gabriel1lima** [Rapsssito/react-native-background-actions#14]
In the sample code, in package.json, the dependencies look like this:

```
  "dependencies": {
    ......
    "react-native-background-actions": "https://github.com/Rapsssito/react-native-background-actions#feat-isRunning"
  },
```

When running npm install this error is generated:

```
npm ERR! code 1
npm ERR! Command failed: git checkout feat-isRunning
npm ERR! error: pathspec 'feat-isRunning' did not match any file(s) known to git.
```
So I changed the version to the last one (2.1.0):

```
  "dependencies": {
   ......
    "react-native-background-actions": "2.1.0",
  },
```

So npm install worked normally, but when running react-native run-android, this error is generated:
![Screenshot_20200220-164501_backgroundExample](https://user-images.githubusercontent.com/41576660/74972478-879a7000-5400-11ea-9473-2b34e4dd087f.jpg)

**Comment by Rapsssito** [comment]
@gabriel1lima, I am not able to reproduce the issue. Did you reset the transform cache after installing the last version?

**Comment by gabriel1lima** [comment]
react-native start --reset-cache worked

Sorry for the bad English. I'm Brazilian and I'm using Google Translate.

Thanks!

**Comment by Rapsssito** [comment]
Glad it worked!
