### ISSUE TITLE
How to start service every 3mins

### ISSUE THREAD

**Issue by Karthik-sk25** [Rapsssito/react-native-background-actions#146]
I want to start service for screenshot  every 3mins without delaying.if i use for loop it takes continues screenshot.
const veryIntensiveTask = async taskDataArguments => {
  //   const { delay } = taskDataArguments;
  //   await new Promise(async resolve => {
  //     for (let i = 0; BackgroundService.isRunning(); i++) {
Screenshot.captureScreenshot(1000);    // it means 1sec
}
sleep (delay)

**Comment by nehal7-ml** [comment]
sleep(delay) needs to be inside the for loop I think
 for (let i = 0; BackgroundService.isRunning(); i++) {
Screenshot.captureScreenshot(1000); // it means 1sec
sleep (delay) // delay is provided through parameter arguments when starting the service
}

**Comment by mdrajibcbnits** [comment]
Did anyone actually achieve this???
My case using Simulator background task terminate after 30 min 
Using Real device background task terminate after 30 sec 

If anyone did make it work, please share that. thanks
