### ISSUE TITLE
How to set up Geolocation correctly for iOS

### ISSUE THREAD

**Issue by Rubioli** [Rapsssito/react-native-background-actions#148]
First of all, a great library 💯 

Currently, I'm using [geolocation](https://github.com/michalchudziak/react-native-geolocation) to keep the iOS alive and this is how I do it:
```
const RunCronjob = async () => {
  const sleep = (time) => new Promise((resolve) => setTimeout(() => resolve(), time));
  const myBackgroundJob = async (taskDataArguments) => {
      const { delay } = taskDataArguments;
      await new Promise( async (resolve) => {
          for (let i = 0; BackgroundService.isRunning(); i++) {
            //run geolocation service just in IOS
            if (Platform.OS !== "android") {
              getUserGeoLocation();
            }

            await sleep(delay);
          }
      });
  };

  const options = {
      taskName: 'myCrons',
      taskTitle: 'title',
      taskDesc: 'desc',
      taskIcon: {
          name: 'ic_app_notification',
          type: 'drawable',
      },
      color: '#ff8e23',
      linkingURI: 'app://',
      parameters: {
          delay: 4 * 60 * 1000
      },
  };

  // iOS only Listen for the iOS-only expiration handler that allows you to 'clean up' shortly before the app’s remaining background time reaches 0
  if (Platform.OS !== "android") {
    BackgroundService.on('expiration', () => {
       getUserGeoLocation();
    });
  }

  
  if (!BackgroundService.isRunning()) {
    await BackgroundService.start(myBackgroundJob, options);

    await BackgroundService.updateNotification(); // Only Android, iOS will ignore this call
  }
}

const getUserGeoLocation = () => {
  Geolocation.getCurrentPosition(
    success => {
      console.log(success);
    },
    error => {
      console.log("geoError", error);
    },
    {enableHighAccuracy: true, timeout: 20000, maximumAge: 1000}
  );
}
```
I set it inside the job runner to run it every 5 minutes. Is this the correct way of doing this?

But the issue is that in the background, I don't get anything and don't seem to run, even though I have allowed everything.

My `info.plist`:
```
	<key>NSLocationAlwaysAndWhenInUseUsageDescription</key>
	<string>1</string>
	<key>NSLocationAlwaysUsageDescription</key>
	<string>1</string>
	<key>NSLocationWhenInUseUsageDescription</key>
	<string>1</string>
```

Appreciate any feedback! Thanks in advance

**Comment by ahummel25** [comment]
@Rubioli Did you happen to get this working while the app is closed? I'm trying to do something very similar.

**Comment by Rubioli** [comment]
No @ahummel25 No still struggling :/

**Comment by Rubioli** [comment]
@rogeriocassares we would appreciate if you could add a example for implementing this for iOS as well

**Comment by Rubioli** [comment]
Thank you so much @rogeriocassares for your reply. I have a Mac myself and it would be my pleasure to find a way to fix an example.

I have done it previously by using screen share and also VSCode Liveshare and it's much less painless than it sounds ;) Basically to set up a collab-env.

Let me know if you are interested and we can make it happen together 💯

**Comment by matheusyuri7** [comment]
@Rubioli @ahummel25  have you found a way to keep the app running on ios in the background?

I am developing a fitness app, but I haven't been able to do this yet.
I tried many libraries, but they all stopped working after a period of time

**Comment by Rubioli** [comment]
No not yet and the bigger issue is actually the app store itself, because
they don't allow it.

I think the best is to have someone write a ios component. Its costly and
maybe we can do something together if you are into it

**Comment by matheusyuri7** [comment]
Hello @Rubioli ! I found a way to get the user`s geolocation and do some operations in background using the same library you are using ([react-native-geolocation-service](https://github.com/Agontuk/react-native-geolocation-service))
There is a method called watchPosition that will give you the user's location frequently. As I understand it here, it will not always run at a specific interval, but will continue to run in the background until you stop the service. Here is an example:
[example code](https://github.com/Agontuk/react-native-geolocation-service/blob/master/example/src/App.tsx)

You just need to configure your XCode enabling Background Modes and Location Updates on Capabilities

Feel free to contact me if you have any doubts

**Comment by Rubioli** [comment]
Thanks man. Appreciate it. I used the same geo location approach first, but
when I submitted to app store, they forced me to remove it because you need
to have a specific need for getting user's location constantly :/
