### ISSUE TITLE
Process is running in background but no notification is seen in IOS device?

### ISSUE THREAD

**Issue by vipulSoni458** [Rapsssito/react-native-background-actions#150]

**Comment by vipulSoni458** [comment]
Hello I am using this example :
import BackgroundService from 'react-native-background-actions';

let sleep = ms => new Promise(resolve => setTimeout(resolve, ms));

const veryIntensiveTask = async taskDataArguments => {
  const {delay} = taskDataArguments;
  await new Promise(async resolve => {
    for (let i = 0; BackgroundService.isRunning(); i++) {
      console.log(i);
      await BackgroundService.updateNotification({taskDesc: 'Runned -> ' + i});
      await sleep(delay);
    }
    resolve();
  });
};

const options = {
  taskName: 'Example',
  taskTitle: 'ExampleTask title',
  taskDesc: 'ExampleTask description',
  taskIcon: {
    name: 'ic_launcher',
    type: 'mipmap',
  },
  color: '#ff00ff',
  linkingURI: 'yourSchemeHere://chat/jane', // See Deep Linking for more info
  parameters: {
    delay: 1000,
  },
};

const start = () => {
  BackgroundService.start(veryIntensiveTask, options);
};
const stop = () => {
  BackgroundService.stop();
};

and on click of start button I am starting the background service in IOS, as I can see in terminal console value is printing but when I minimize the app in background process is still running and I can see the console count value increasing but I am printing this   await BackgroundService.updateNotification({taskDesc: 'Runned -> ' + i}); in notitication but its not printing. can anyone help me on this. It would be very helpful if someone can guild me through this what I am doing wrong. Thank you

**Comment by maxckelly** [comment]
I'm getting the same issue, have you found a solution?

**Comment by smiley717** [comment]
Same to me as well.

**Comment by Rapsssito** [comment]
The notification is only visible in Android. I have updated the documentation.
