### ISSUE TITLE
The screen randomly turns on when the process is running.

### ISSUE THREAD

**Issue by remirez** [Rapsssito/react-native-background-actions#152]
On an android phone. When I start my background task and then lock the phone, it will occasionally and randomly turn the screen on. Is this a known behavior? Is there a way around this so that the screen stays off even when the task is running?

**Comment by Rapsssito** [comment]
@remirez, this is probably heavily dependent on the OS and the device's settings. It is possible that an update in the notification turns on the screen (like a new notification).
