### ISSUE TITLE
Not working when phone screen is off

### ISSUE THREAD

**Issue by SurajMohanty02** [Rapsssito/react-native-background-actions#157]
Hii, This package works fine when screen is on . But if i lock the device means it is not working. Can you please suggest me any solution ?

**Comment by Navicna** [comment]
Ios, android or both?

**Comment by SurajMohanty02** [comment]
I've tested on Android

**Comment by judaihyun** [comment]
notification is show?  
-> android only work. when notification show

may be api v12??(i don't remember) above, you must setting battery optimization ( set : always on )

**Comment by natemartins** [comment]
I'm experiencing same issues. @SurajMohanty02 were you able to resolve this?

**Comment by Navicna** [comment]
Make sure these steps are configured correctly:
![image](https://user-images.githubusercontent.com/52223211/216436364-8b3cc5b4-2be7-4ad1-ba23-a16789aece8d.png)

**Comment by natemartins** [comment]
Yea. I have these configured correctly but still nothing.

**Comment by bobo717** [comment]
the same

**Comment by hraschan** [comment]
Any solutions so far?

**Comment by SurajMohanty02** [comment]
> w

Are you using this library for getting location ? If so then use react-native-get-location

**Comment by theopham** [comment]
The same

**Comment by tranminhnhat1005** [comment]
You need to turn off battery Optimization or Power Saving Mode for your app in Setting, if you using android 13, let check the notification, background actions need the notification.
