### ISSUE TITLE
Is it possible to start the service without displaying a notification?

### ISSUE THREAD

**Issue by gabriel1lima** [Rapsssito/react-native-background-actions#16]

**Comment by Rapsssito** [comment]
@gabriel1lima, sadly **it is not possible to start the service without having the notification** on Android. Taken from the [Android Developer Docs](https://developer.android.com/guide/components/services#Foreground):

> A foreground service is a service that the user is actively aware of and isn't a candidate for the system to kill when low on memory. A foreground service must provide a notification for the status bar, which is placed under the Ongoing heading. This means that the notification cannot be dismissed unless the service is either stopped or removed from the foreground.

**Comment by pholyheang** [comment]
The service is not auto start after reboot

**Comment by ydv0121** [comment]
> The service is not auto start after reboot

Did you figure out how to do it?
