### ISSUE TITLE
react-native-background-actions:compileReleaseJavaWithJavac

### ISSUE THREAD

**Issue by kamatcho** [Rapsssito/react-native-background-actions#162]
app can't compile because of 

RNBackgroundActionsTask.java:45: error: cannot find symbol
            contentIntent = PendingIntent.getActivity(context, 0, notificationIntent, PendingIntent.FLAG_MUTABLE);
                                                                                                   ^
  symbol:   variable FLAG_MUTABLE
  location: class PendingIntent

**Comment by kamatcho** [comment]
**Issue Still Exists With Two Errors :-** 
ode_modules/react-native-background-actions/android/src/main/java/com/asterinet/react/bgactions/RNBackgroundActionsTask.java:44: error: cannot find symbol
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
                                                        ^
  symbol:   variable S
  location: class VERSION_CODES



node_modules/react-native-background-actions/android/src/main/java/com/asterinet/react/bgactions/RNBackgroundActionsTask.java:45: error: cannot find symbol
            contentIntent = PendingIntent.getActivity(context, 0, notificationIntent, PendingIntent.FLAG_MUTABLE);
                                                                                                   ^
  symbol:   variable FLAG_MUTABLE
  location: class PendingIntent

**Comment by Rapsssito** [comment]
@kamatcho, you are right. In the meantime, I highly recommend you use [v2.6.7](https://github.com/Rapsssito/react-native-background-actions/releases/tag/v2.6.7).

**Comment by Navicna** [comment]
I have the same issue, but v2.6.7 and update rn background actions but is not work for me.
