### ISSUE TITLE
Multi timer?

### ISSUE THREAD

**Issue by Bobo-amg** [Rapsssito/react-native-background-actions#166]
Just politely asking why no multi timer option available? Seems like the next logical step.

Or is this package now in 'maintenance' mode?

**Comment by Rapsssito** [comment]
Hi @Bobo-amg, you can use the same background task to run multiple timers.

**Comment by ogtfaber** [comment]
@Bobo-amg thanks for the answer; would be good to clarify in the docs. And thanks for the library! For whatever reason the Expo team does not provide this functionality in their standard suite background packages while it seems to be a pretty common use case.
