### ISSUE TITLE
Background job is not working while Application is in kill mode in IOS.

### ISSUE THREAD

**Issue by VaishaliG2020** [Rapsssito/react-native-background-actions#169]
"react": "16.13.1",
  "react-native": "0.63.3",
  "react-native-background-actions": "^3.0.0",

**Comment by Rapsssito** [comment]
@VaishaliG2020, when the app is killed by the user, iOS will close all running background tasks.

**Comment by korzonkiee** [comment]
> @VaishaliG2020, when the app is killed by the user, iOS will close all running background tasks.

Hey @Rapsssito! Sorry to bother, but do you know a place in the official documentation where it's clearly stated that killing the app by the user (swiping it up from task manager) closes all running background tasks? I am aware that's the case, although I cannot find it anywhere in the docs 😅
