### ISSUE TITLE
BackgroundService.start create multiple task 

### ISSUE THREAD

**Issue by killem2000** [Rapsssito/react-native-background-actions#170]
When I kill my application and open it again and run BackgroundService.start it creates 2 tasks, even running BackgroundService.stop

**Comment by BillDelvin** [comment]
Hi.. I'm face the same issue, is there any way to solve this problem ?

**Comment by alexfov** [comment]
Duplicate
https://github.com/Rapsssito/react-native-background-actions/issues/121 here is the original issue. It's not solved yet.

**Comment by Lunatic-coder001** [comment]
But know I think the problem of multiple task running simuntenously is solved  and my code was this 
useEffect(() => {
    Linking.getInitialURL().then(url => {
      console.log("uuu", url)
      if (url !== null) {
        // if opened from notification if app is killed

      }
    }).catch(err => console.error('An error occurred', err));
    let subcribtion = Linking.addEventListener('url', handleOpenURL);
    subcribtion.subscriber;

    return () => {
      subcribtion.remove();
    };
  }, []);
  // Linking.addEventListener('url', handleOpenURL);

  function handleOpenURL(evt) {
    // Will be called when the notification is pressed foreground
    console.log(evt.url);
    // do something
  }
is my code not working properly

**Comment by mlwong54** [comment]
Hi. Encounter the problem. I tried adding a delay function after the stop call.
Sometimes it works but sometimes the task is not properly killed.
There are still multiple task happening.
