### ISSUE TITLE
Doesn't work on android 12

### ISSUE THREAD

**Issue by traxx10** [Rapsssito/react-native-background-actions#172]
Hello and good day, thanks for the wonderful library but it currently doesn't work on my android 12 device. I have been using it on android 11 and below and it works fine.

I'm running the example code, It specifically stops working once i minimise or kill the app.

**Comment by robertsonasc** [comment]
Oh, that's why it's not working for me, i am in Android 12. Sad... I will go search how I can get around this problem.

**Comment by Rapsssito** [comment]
Closing as duplicate of #168.
