### ISSUE TITLE
Background task gets closed automatically

### ISSUE THREAD

**Issue by myzow** [Rapsssito/react-native-background-actions#176]
Hello i've used this package to send the data from app to server it sends data to the server even after killing the app it's working fine but after some hours it gets closed can you please help me if this is a package issue or some restrictions are placed here from android. Thanks

**Comment by carbseater** [comment]
Yeah I'm facing the same issue, and I'm using Android 13 and it kills the background task in 5 minute @myzow

**Comment by SurajMohanty02** [comment]
Same issue i'm also facing . Please help

**Comment by Rapsssito** [comment]
@myzow, @carbseater and @SurajMohanty02, your OS' battery management might be closing the background tasks. If you want to avoid this, you might have to set up an exception for unrestricted battery usage for your app.

**Comment by CedricBrandt** [comment]
Mine gets closed - even though i have unrestricted battery usage enabled - after a few hours. When i go to sleep and wake up in the morning the apps background task is always inactive and needs to be restarted.

**Comment by anonymous-OO7** [comment]
Hello everyone! Have you all found a working solution yet? I am facing same.   @myzow  @Rapsssito @CedricBrandt
