### ISSUE TITLE
iOS Battery issue

### ISSUE THREAD

**Issue by riyasolanki** [Rapsssito/react-native-background-actions#177]
Hello,

When I use this package I'm getting battery issue in iOS side reason is app background service is all time running. for Android I'm using react-native-disable-battery-optimizations-android this package to solve battery issue but I didn't found any solution for iOS. 

In my app I need to allow updated our current location in every time when is app in background also.

"react-native-background-actions": "^2.6.7",

**Comment by Rapsssito** [comment]
@riyasolanki, I am sorry, but you should probably use another module more targeted to geolocalization with background capabilities.
