### ISSUE TITLE
Not Working in Android 13 and OnePlus

### ISSUE THREAD

**Issue by Sagar6228** [Rapsssito/react-native-background-actions#178]
I am not getting the Notification for the background Task in android 13 and Oneplus

**Comment by carbseater** [comment]
Take request POST_NOTIFICATION permission at runtime from user first then only you will see notification

```
async function requestPostNotification() {
  try {
    const granted = await PermissionsAndroid.request(
      PermissionsAndroid.PERMISSIONS.POST_NOTIFICATIONS,
      {
        title: "Notification",
        message: "Please allow to show notifications",
        buttonNeutral: "Ask Me Later",
        buttonNegative: "Cancel",
        buttonPositive: "OK"
      }
    );
    if (granted === PermissionsAndroid.RESULTS.GRANTED) {
      console.log("Notification permission granted");
    } else {
      console.log("Notification permission denied");
    }
  } catch (err) {
    console.warn(err);
  }
}
```

**Comment by Sagar6228** [comment]
> Take request POST_NOTIFICATION permission at runtime from user first then only you will see notification
> 
> ```
> async function requestPostNotification() {
>   try {
>     const granted = await PermissionsAndroid.request(
>       PermissionsAndroid.PERMISSIONS.POST_NOTIFICATIONS,
>       {
>         title: "Notification",
>         message: "Please allow to show notifications",
>         buttonNeutral: "Ask Me Later",
>         buttonNegative: "Cancel",
>         buttonPositive: "OK"
>       }
>     );
>     if (granted === PermissionsAndroid.RESULTS.GRANTED) {
>       console.log("Notification permission granted");
>     } else {
>       console.log("Notification permission denied");
>     }
>   } catch (err) {
>     console.warn(err);
>   }
> }
> ```

Showing Permission is Null

**Comment by chqamarali** [comment]
> async function requestPostNotification() {
>   try {
>     const granted = await PermissionsAndroid.request(
>       PermissionsAndroid.PERMISSIONS.POST_NOTIFICATIONS,
>       {
>         title: "Notification",
>         message: "Please allow to show notifications",
>         buttonNeutral: "Ask Me Later",
>         buttonNegative: "Cancel",
>         buttonPositive: "OK"
>       }
>     );
>     if (granted === PermissionsAndroid.RESULTS.GRANTED) {
>       console.log("Notification permission granted");
>     } else {
>       console.log("Notification permission denied");
>     }
>   } catch (err) {
>     console.warn(err);
>   }
> }

You should need to add permission in AndroidManifest.xml
<uses-permission android:name="android.permission.POST_NOTIFICATIONS"/>
