### ISSUE TITLE
Android 12+ background service isn`t working 

### ISSUE THREAD

**Issue by JASIM0021** [Rapsssito/react-native-background-actions#181]
when leave from  the app that mean when I am  click the home button of my android 12+ then the bg service isn`t working

**Comment by chairmanqcy** [comment]
i get the same problem too

**Comment by SurajMohanty02** [comment]
same issue

**Comment by lesleysin** [comment]
Try add this one to your application manifest.xml
`<service android:name="com.asterinet.react.bgactions.RNBackgroundActionsTask" />`
This solution solved my problem

**Comment by Rapsssito** [comment]
Fixed by #184

**Comment by JASIM0021** [comment]
> 

thanks buddy
