### ISSUE TITLE
Background tasks not working when device is locked & if device is unlocked working differently Android 12

### ISSUE THREAD

**Issue by aarish-rajput** [Rapsssito/react-native-background-actions#185]
**_Hey Good day!_**

I am using Android 12 I am executing a task after every 10 second. but when my device is unlock it executes after 2-10 mins not after 15seconds or any uniform time. And if the device is locked it doesn't execute any task. Please provide any solution doesn't matter if it is any permission or extra code.

**Comment by Rapsssito** [comment]
@aarish-rajput, this is uncontrollable from the developer perspective. The OS decides when and how the background tasks are executed. One possibility to mitigate this problem is to whitelist the app in the battery restrictions.
