### ISSUE TITLE
Geolocation is not working as a task in my android 12 emulator(for now)

### ISSUE THREAD

**Issue by aarish-rajput** [Rapsssito/react-native-background-actions#186]
**_Hey Good day!_**

I am using react-native-background-actions for background task and @react-native-community/geolocation for getting location. I want to send latitude and longitude to backend after every 1-10mins even if the app is closed. But it is working fine if the app is running but if the app is closed the geolocation task is not working but api call task works fine alone. when I open the app then it suddenly triggers all missed geolocation task. like 5 geolocation task a time. Please help me with any solution like any other geolocation library or any permission.

**Comment by Rapsssito** [comment]
@aarish-rajput, I am sorry, but this library is not specialized in this use-case. Please, use another library that specializes in timed background jobs.

**Comment by VTSingle** [comment]
@aarish-rajput Hey, did you find a solution for your case?
