### ISSUE TITLE
Background task runs in android even if the app is closed but not in iOS.

### ISSUE THREAD

**Issue by Irfanwani** [Rapsssito/react-native-background-actions#189]
How to run the background task even if the app is closed on iOS.

**Comment by mohammadrajabraza** [comment]
Hey @Irfanwani, found this on the documentation. I hope this will might help.
<img width="1395" alt="Screenshot 2023-07-26 at 1 42 17 PM" src="https://github.com/Rapsssito/react-native-background-actions/assets/11742902/0fe3f15f-7957-4cb3-83c5-2f32500a7c64">

**Comment by arifrohmanhakim** [comment]
Hi, @Irfanwani 
Could you provide me with an example code, please?
I've attempted it, but I'm facing issues on both Android and iOS.

The 'veryIntensiveTask' doesn't seem to be triggering, and the notifications aren't appearing either

**Comment by Irfanwani** [comment]
I just tried the basic code provided in the readme of this package and that worked for me for android but not for ios

**Comment by weloli6991** [comment]
@Rapsssito any updates?

**Comment by poulimainfotech** [comment]
any updates for ios ?

**Comment by Qurat-ul-ainn** [comment]
> How to run the background task even if the app is closed on iOS.

did u resove it?

**Comment by sanjaymojro** [comment]
@Rapsssito any updates on this for iOS?

**Comment by klayverxd** [comment]
any updates for ios?
