### ISSUE TITLE
📱 Background Task it working, but Notification now showing on IOS.

### ISSUE THREAD

**Issue by smiley717** [Rapsssito/react-native-background-actions#190]
Hello, It's working fine with android, but I am having some troubles to use this library on IOS. It looks like the background task works, but the notification is not being shown like android. can anyone tell me is it supposed to show or not?
![image](https://github.com/Rapsssito/react-native-background-actions/assets/80674675/ad7f276c-9649-4895-b3f8-eb7e6365d3de)

**Comment by mohammadrajabraza** [comment]
Hey @smiley717 , I think this is he mentioned in the docs that Notification Icon and progressbar are Android only.
<img width="1395" alt="Screenshot 2023-07-26 at 1 42 17 PM" src="https://github.com/Rapsssito/react-native-background-actions/assets/11742902/32d39538-8a33-4eff-9a97-08285787919f">

**Comment by smiley717** [comment]
Yes, I confirmed it only works with android. Thank you @mohammadrajabraza

**Comment by Rapsssito** [comment]
The notification is only visible in Android. I will update the documentation.
