### ISSUE TITLE
Background Task got killed when user release the app from RAM in IOS.  Android working fine

### ISSUE THREAD

**Issue by MalhotraKunal** [Rapsssito/react-native-background-actions#193]
Background task not woking after 30s in IOS, when user leave the forground.

**Comment by rajkumar004** [comment]
On my side, Also in android, task got killed, when releasing the app.

**Comment by MalhotraKunal** [comment]
@rajkumar004 Go to the app settings se if you have allow "background activity" in side battery usage in android.
