### ISSUE TITLE
Not work in android 13

### ISSUE THREAD

**Issue by kabitacode** [Rapsssito/react-native-background-actions#195]
Hi, thanks for creating this awesome package, but there was a problem running it.

FAILURE: Build failed with an exception.

What went wrong:
Execution failed for task ':react-native-background-actions:compileDebugJavaWithJavac'.
Compilation failed; see the compiler error output for details.

`node_modules/react-native-background-actions/android/src/main/java/com/asterinet/react/bgactions/RNBackgroundActionsTask.java:44: error: cannot find symbol
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
                                                        ^
  symbol:   variable S
  location: class VERSION_CODES`

`error: cannot find symbol
  contentIntent = PendingIntent.getActivity(context, 0, notificationIntent, PendingIntent.FLAG_MUTABLE);
`
                                                                                                   ^
  symbol:   variable FLAG_MUTABLE
  location: class PendingIntent
2 errors

       in my android/build.gradle :

       buildToolsVersion = "30.0.2"
        minSdkVersion = 21
        compileSdkVersion = 33 
        targetSdkVersion = 33

**Comment by Sravansuhas** [comment]
Even i'm not sure what went wrong in your case, Even i'm also using Android 13, I'm not facing any issues. Can you uninstall and install the lib and make sure you implemented every step mention in the installation guide. Still, if you're facing the error, try to create an example project and run the lib again.

**Comment by Rapsssito** [comment]
Should be fixed by #208
