### ISSUE TITLE
When turn off the Android 13 device, the app not working

### ISSUE THREAD

**Issue by tranminhnhat1005** [Rapsssito/react-native-background-actions#196]
I'm creating a tracking running app, the problem is about the **Android 13** update. 

- I was requested the _Always allow_ for **Location Permission**
- Disabled the _Battery Optimization_ following the documents of [Notifee](https://notifee.app/react-native/docs/android/background-restrictions) 

But sometimes the app still be killed by the system of the device.

**Comment by Rapsssito** [comment]
This is common, as the OS has absolute control over the background processes of the device. https://github.com/Rapsssito/react-native-background-actions/issues/22#issuecomment-628737527
