### ISSUE TITLE
Stopping after 5 min in background, (React Native) Android

### ISSUE THREAD

**Issue by zahoormohammed** [Rapsssito/react-native-background-actions#197]
i am using latest version of this library i.e 3.0.1. when the app is open it is working perfectly, when i am closing the app in background  it is working just 5mins then notification is not showing and background task is not working after 5mins.
please help me to fix this issue, 
My android is Android 13,and mobile is  Iqoo z6 5h

**Comment by SurajMohanty02** [comment]
Same thing happened in my case also . I'm using 3.0.0 version of this library . My android version 13 and device name One Plus Nord 2T. It worked for 30 mins and after that it stopped, Please help me .

**Comment by niftytushar** [comment]
Facing the same issue

**Comment by Gurwinder-Espranza** [comment]
Anyone did resolve it?

**Comment by kurdev2020** [comment]
Facing the same issue , it worked for a few days

**Comment by Rapsssito** [comment]
This is common, as the OS has absolute control over the background processes of the device. See https://github.com/Rapsssito/react-native-background-actions/issues/22#issuecomment-628737527
