### ISSUE TITLE
TypeError cannot read property 'start' of null

### ISSUE THREAD

**Issue by Joaquim-Frances** [Rapsssito/react-native-background-actions#199]
Hello I'm getting always this error: TypeError cannot read property 'start' of null

![image](https://github.com/Rapsssito/react-native-background-actions/assets/72190276/313d5f0f-cb1a-49a3-8815-6640a7bfa85b)

I checked everything many times and looks in place. Any help?

**Comment by kreativeAfaq** [comment]
same issue

**Comment by gabrielpdsilva** [comment]
After adding the lib, try uninstalling the app and install it again. In android for example, after uninstalling it just run:
```
yarn android
yarn start
```

**Comment by kaifussain** [comment]
And i'm getting this error! 
TypeError: Cannot read property **'stop'** of null

**Comment by vincon09** [comment]
> And i'm getting this error! `TypeError: Cannot read property 'stop' of null`

did you find any solution?
