### ISSUE TITLE
background service is not running anymore when app minimized

### ISSUE THREAD

**Issue by juntiapps** [Rapsssito/react-native-background-actions#202]
background task is not running anymore when app minimized. it still running in emulator. but not running in real device. 
RN 0.72, device poco x3

**Comment by onderbakirtas** [comment]
Bump message for issue, affects me as well.

React Native 0.72, Samsung Galaxy S23

**Comment by Sahilcf** [comment]
Same here
React native 0.72, Redme Note 10 pro

**Comment by alan-nugraha** [comment]
same issue, i using react-native 0.68.2

**Comment by apapalillo** [comment]
Hi, I've spent hours debugging why the service didn't start after upgrading React Native.

In the end, I've figured out that I needed to add an exclusion in the proguard file:

```
# React Native Background Actions
-keep public class com.asterinet.react.bgactions.** {*;}
```

Hope this works for you too.

**Comment by Rapsssito** [comment]
This is common, as the OS has absolute control over the background processes of the device. See https://github.com/Rapsssito/react-native-background-actions/issues/22#issuecomment-628737527
