### ISSUE TITLE
[Question] Is it possible to use this module for using microphone when app is killed?

### ISSUE THREAD

**Issue by alexzborovskii** [Rapsssito/react-native-background-actions#205]
I'm using react-native-voicebox-speech-rec module to recognize text in background and trigger alarms when something dangerious was said. 
Everithing works fine in foreground and background, but when I kill the app, microphone is also tunring off, no matter what I do. The counter in norification continues to count.
Does "UI" include microphone, so I cant touch it with react-native-background-actions?

Maybe I should start the procces in a different way? 
This is my task:

```
`await new Promise(async resolve => {

        // open microphone, start recognize. works when app isn't killed
        startSpeechRecognition(); 

        // loop that works always
        for (let i = 0; BackgroundService.isRunning(); i++) {
          console.log('Runned -> ', i);
          await BackgroundService.updateNotification({ taskDesc:  ' i -> ' + i});
          await sleep(delay);
        }
      });`
```

**Comment by nihilanthmf** [comment]
Have you found a solution yet? I will be forever grateful!

**Comment by alexzborovskii** [comment]
@nihilanthmf not yet. but I'm still working on it. If I'll achieve something, I'll let you know!

**Comment by nihilanthmf** [comment]
@alexzborovskii gotcha! Let me know when it's done, will help my app a lot! Thanks for developing such an amazing package!

**Comment by alexzborovskii** [comment]
@nihilanthmf Hi! This part of my project is finaly working. 
I ended up using @voximplant/react-native-foreground-service (from here [)](https://github.com/Raja0sama/rn-foreground-service) instead of this module. Probably my problem with this module was not in it, but in speech recognition, but I have no mood to check it after all this pain :). 
Not every voice recognition module could work with it, but at the end of the day it works perfect for me. 
Good luck to you!
