### ISSUE TITLE
How to Hide this nofiication By default

### ISSUE THREAD

**Issue by muralikrishnakandala** [Rapsssito/react-native-background-actions#212]
![Bg NOTIFICATION](https://github.com/Rapsssito/react-native-background-actions/assets/124434709/e8099e81-dd09-44fa-9501-6c5fb0987672)

@Rapsssito Can you please help me out on this, How to hide this notification.

**Comment by rsroffrove** [comment]
Can we hide this notification by any chance? It doesn't appear on IOS but for Android there is no option to hide it.

**Comment by Hidayat112** [comment]
Did you find anything related to it ?

**Comment by MAhnaf** [comment]
Any Updates here ?

**Comment by KaiValar** [comment]
By as i know, the persistent notification is required as long as the job is running by Android itself, so i don't think we can hide it :( If anyone success hiding will be a hero.

**Comment by Rapsssito** [comment]
Sadly it is not possible to start the service without having the notification on Android. See #16
