### ISSUE TITLE
Background action stops in OPPO F9 Pro

### ISSUE THREAD

**Issue by ravithesun02** [Rapsssito/react-native-background-actions#22]
Background actions starts but it gets stopped after certain time in android 9 
. It works fine in all other versions.

**Comment by Rapsssito** [comment]
@ravithesun02, thanks for the feedback! Could you provide more info about your issue: devices tested, code, etc?

**Comment by ravithesun02** [comment]
I have tested on different phones 
It worked well on Moto e4 (Android 7)
. It didn't work on oppo F9 pro (Android version 9).It starts well but on clearing the recents on phone 
BackgroundTask notification disappears.

**Comment by Rapsssito** [comment]
@ravithesun02, sorry, I didn't understand what you meant by 'clear the recents'. Could you provide the steps to reproduce the bug?

**Comment by ravithesun02** [comment]
I mean when i remove all the apps from background.
somewhere i read that all the chinese phone remove all the backgroound task to optimize the performance.

**Comment by Rapsssito** [comment]
**If you remove an app from the background all the background tasks created from that app become a target to be removed**. The OS will always have the last word on background services, and some manufactures might be more aggressive with the optimizations than others.

Does this also happen without removing the app from the background?

**Comment by ravithesun02** [comment]
Nope .
So if i use this with react native queue package will the issue be fixed

**Comment by Rapsssito** [comment]
@ravithesun02, that library looks unmaintained, but you can try! But as I said, I think the issue is more with the OS service management than with the React Native library itself.

> The Android system stops a service only when memory is low and it must recover system resources for the activity that has user focus. If the service is bound to an activity that has user focus, it's less likely to be killed; if the service is declared to run in the foreground, it's rarely killed. If the service is started and is long-running, the system lowers its position in the list of background tasks over time, and the service becomes highly susceptible to killing

You can read more [here](https://developer.android.com/guide/components/services.html#Basics).

**Comment by ravithesun02** [comment]
@Rapsssito i want access continuous location data even when app is killed . This package works well android version other than 9 . Even it works well on 10 . 
I went through other packages too .
Can you please help me in this.

**Comment by Rapsssito** [comment]
@ravithesun02, as I said, I don't think it is the OS version. The issue might be related to the device manufacturer and the modifications they made on the base Android.
For location data you could use [react-native-location](https://github.com/timfpark/react-native-location) and follow the library's instructions. It might work even when the app has been killed because geolocalization is a special background service (high-priority).
