### ISSUE TITLE
react-native-background-actions  4.0.0 is Not working with Android 14 App Crash issue

### ISSUE THREAD

**Issue by SaGaR1084** [Rapsssito/react-native-background-actions#227]
Android version details:-

    buildToolsVersion = "34.0.0"
    minSdkVersion = 23
    compileSdkVersion = 34
    targetSdkVersion = 34
    ndkVersion = "26.1.10909125"
    kotlinVersion = "1.9.22"
    
package version details:-

    "react": "18.2.0",
    "react-native": "0.74.2",
    "react-native-background-actions": "^4.0.0",
    
Getting Error:-

<img width="1587" alt="Screenshot 2024-06-26 at 11 46 04 AM" src="https://github.com/Rapsssito/react-native-background-actions/assets/34228088/e92fc2bc-5ae9-495c-bd45-55d2a2debb00">

**Comment by vzkharov** [comment]
Maybe problem with `react-native@0.74`.
I have an error because of this, just downgrade to `0.73.6`

Can you share your manifest?

**Comment by SaGaR1084** [comment]
<manifest xmlns:tools="http://schemas.android.com/tools"
  xmlns:android="http://schemas.android.com/apk/res/android">

  <uses-permission android:name="android.permission.INTERNET" />
  <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
  <uses-permission android:name="android.permission.BODY_SENSORS" />
  <uses-permission android:name="android.permission.BODY_SENSORS_BACKGROUND" />
  <uses-permission android:name="android.permission.POST_NOTIFICATIONS" />

  <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
  <uses-permission android:name="android.permission.VIBRATE" />
  <uses-permission android:name="android.permission.WAKE_LOCK" />
  <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
  <uses-permission android:name="android.permission.SCHEDULE_EXACT_ALARM" />
  <uses-permission android:name="android.permission.USE_EXACT_ALARM" />
  <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
  <uses-permission android:name="android.permission.ACTIVITY_RECOGNITION" />

  <uses-feature android:name="android.hardware.sensor.stepcounter" android:required="false" />
  <uses-feature android:name="android.hardware.sensor.accelerometer" android:required="true" />

  <application android:name=".MainApplication" android:label="@string/app_name" android:icon="@mipmap/ic_launcher" android:roundIcon="@mipmap/ic_launcher_round" android:allowBackup="false" android:theme="@style/AppTheme">
    <activity android:name=".MainActivity" android:label="@string/app_name" android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|screenSize|smallestScreenSize|uiMode" android:launchMode="singleTask" android:windowSoftInputMode="adjustResize" android:exported="true">
      <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
        <action android:name="androidx.health.ACTION_SHOW_PERMISSIONS_RATIONALE" />
      </intent-filter>
    </activity>


    <meta-data android:name="google_analytics_adid_collection_enabled" android:value="false" />
    <meta-data android:name="com.dieam.reactnativepushnotification.notification_channel_name" android:value="NotificationDemo"/>
    <meta-data android:name="com.dieam.reactnativepushnotification.notification_channel_description" android:value="NotificationDemo Notifications"/>
    
    <meta-data android:name="com.dieam.reactnativepushnotification.notification_color" android:resource="@android:color/white"/>

    <receiver android:name="com.google.android.gms.gcm.GcmRecreiver" android:exported="true" android:permission="com.google.android.c2dm.permission.SEND" tools:ignore="MissingClass">
      <intent-filter>
        <action android:name="com.google.android.c2dm.intent.RECEIVE" />
        <category android:name="${applicationId}" />
      </intent-filter>
    </receiver>

    <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationPublisher" />
    <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationBootEventReceiver" android:exported="false">
      <intent-filter>
        <action android:name="android.intent.action.BOOT_COMPLETED" />
      </intent-filter>
    </receiver>
    <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
    <service android:name=".RNBackgroundActionsTask"/>
    <service android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationRegistrationService" tools:ignore="MissingClass" />
    <service android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationListenerServiceGcm" android:exported="false" tools:ignore="MissingClass">
      <intent-filter>
        <action android:name="com.google.android.c2dm.intent.RECEIVE" />
      </intent-filter>
    </service>

  </application>
</manifest>

**Comment by vzkharov** [comment]
The manifest is missing
```xml
<service android:name="com.asterinet.react.bgactions.RNBackgroundActionsTask" android:foregroundServiceType="..."  />
```

**Comment by albertalef** [comment]
@chenkuangkuang Did u got the answer? I writen the same here, but still crashing
