### ISSUE TITLE
Android Background job is running, but not posting the data when app killed/closed

### ISSUE THREAD

**Issue by ramemandi** [Rapsssito/react-native-background-actions#23]
Hi ,
I am working on react-native , in my android app i installed react-native-background-actions module.
Notification is appears on the top  and i am able to post some data to the backend , when app is in foreground, background(minimized mode),
but when the app is killed/ closed , the notification still appears but the data is not posting to the backend.
pls help ?

**Comment by Rapsssito** [comment]
@ramemandi, take a look at https://github.com/Rapsssito/react-native-background-actions/issues/22#issuecomment-628154260
