### ISSUE TITLE
Automatically stop the service at the end of the process

### ISSUE THREAD

**Issue by luigbren** [Rapsssito/react-native-background-actions#24]
when sending the information to the server I do a process to convert some files and when the process is finished I want to finish the service and remove the icon in the notification, all automatically, because if the user closes the application while the conversion process is performed there is no possibility of finishing the service when the process is finished, I tried the example code and it works fine, but it is manual, activates and deactivates the service by a button with the app open

```
const sleep = time => new Promise(resolve => setTimeout(() => resolve(), time));
const options = {
    taskName: 'Convert',
    taskTitle: 'Converting files',
    taskDesc: 'ExampleTask desc',
    taskIcon: {
        name: 'ic_launcher',
        type: 'mipmap',
    },
    color: '#ff00ff',
    parameters: {
        delay: 1000,
    },
};

const convertingTask = async (taskData) => {
    const {delay} = taskData;
    await new Promise(async (resolve) => {

     //Here I do my conversion and upload processes..
     // Its very good

        await sleep(delay);
    });
    //When the Promise is over with the whole process I want you to stop the Service
    console.log('Stop background service');
    await BackgroundService.stop();


};


await BackgroundService.start(convertingTask, options);         
```

**Comment by Rapsssito** [comment]
@luigbren, you don't need to call `await BackgroundService.stop();` at the end of the background task. Take a look at the [documentation](https://github.com/Rapsssito/react-native-background-actions#usage):
```
// You can do anything in your task such as network requests, timers and so on,
// as long as it doesn't touch UI. Once your task completes (i.e. the promise is resolved),
// React Native will go into "paused" mode (unless there are other tasks running,
// or there is a foreground app).
```

The "paused" mode means that the background service will stop.
