### ISSUE TITLE
[Question] What's the period that the service executes in this package?

### ISSUE THREAD

**Issue by radaalinmihai** [Rapsssito/react-native-background-actions#25]

**Comment by Rapsssito** [comment]
@radaalinmihai, the service will start as soon as you call `BackgroundService.start()` and it will run until the OS kills it, the async task finishes or you call  `BackgroundService.stop()`. Take a look at the [docs](https://github.com/Rapsssito/react-native-background-actions#usage) for more info.

**Comment by radaalinmihai** [comment]
Oh, ok, thank you
