### ISSUE TITLE
[Question] It is possible to keep alive even if user "kills it" 

### ISSUE THREAD

**Issue by samuk190** [Rapsssito/react-native-background-actions#26]
I mean, in the past I saw some applications that to stop the service u need to force close, like uber, google maps.. 
This is possible? 
Btw good lib, its the only one that worked with  Axios Retry. I hope it keeps improving :)

**Comment by Rapsssito** [comment]
@samuk190, those apps are using location data, that's why the OS does not kill them. However, if you remove an app from the background all the background tasks created from that app become a target to be removed. The OS will always have the last word on background services, and some manufactures might be more aggressive with the optimizations (via removing background services) than others.

**Comment by samuk190** [comment]
> @samuk190, those apps are using location data, that's why the OS does not kill them. However, if you remove an app from the background all the background tasks created from that app become a target to be removed. The OS will always have the last word on background services, and some manufactures might be more aggressive with the optimizations (via removing background services) than others.

Ok can you give me a example of how to keep the background task alive if I'm receiving location Data?

If i do background geolocation using @mauron85 lib, the O.S will not kill other task because it is forcing to run background?
I mean if I have two background tasks, one which is location and other is processing, or I need tie them?

**Comment by Rapsssito** [comment]
@samuk190, from my experience, **if you have two background tasks, the OS won't kill any of them**. I am currently using music and processing in the background in one of my projects on production and I have not experience any issue.

**Comment by samuk190** [comment]
> @samuk190, from my experience, **if you have two background tasks, the OS won't kill any of them**. I am currently using music and processing in the background in one of my projects on production and I have not experience any issue.

Thanks. I'm trying to use react-native-background-geolocation from @mauron85 and i think its not possible on the react native version I'm using.
Can you recommend any alternatives?

**Comment by samuk190** [comment]
> @samuk190, from my experience, **if you have two background tasks, the OS won't kill any of them**. I am currently using music and processing in the background in one of my projects on production and I have not experience any issue.

Thank you! I managed to make it work with background and all stuff! 
Your lib is really cool, thanks for maintaning it!

**Comment by Rapsssito** [comment]
> 
> 
> > @samuk190, from my experience, **if you have two background tasks, the OS won't kill any of them**. I am currently using music and processing in the background in one of my projects on production and I have not experience any issue.
> 
> Thanks. I'm trying to use react-native-background-geolocation from @mauron85 and i think its not possible on the react native version I'm using.
> Can you recommend any alternatives? or I can just make an background action that retrieve GPS do until user click stop button?

Sorry, I do not have experience with those kind of libraries. I don't know any alternatives.

**Comment by samuk190** [comment]
> > > @samuk190, from my experience, **if you have two background tasks, the OS won't kill any of them**. I am currently using music and processing in the background in one of my projects on production and I have not experience any issue.
> > 
> > 
> > Thanks. I'm trying to use react-native-background-geolocation from @mauron85 and i think its not possible on the react native version I'm using.
> > Can you recommend any alternatives? or I can just make an background action that retrieve GPS do until user click stop button?
> 
> Sorry, I do not have experience with those kind of libraries. I don't know any alternatives.

I just set Geolocation.WatchPosition inside your background task action and it worked. 

I made a new task in case of GPSdesactivated to try 15 times until it sends with GPS Data! It worked nicely

**Comment by Nahani** [comment]
Hello @samuk190.
I'm interested to your solution.
Where do you put the Geolocation.WatchPosition ?
Can you please share the code ? I'd really appreciate it.

Thank you.

**Comment by samuk190** [comment]
> Hello @samuk190.
> I'm interested to your solution.
> Where do you put the Geolocation.WatchPosition ?
> Can you please share the code ? I'd really appreciate it.
> 
> Thank you.
```
useMemo(() => {
    verifyLocationPermission();
    // BackgroundService.start(taskGPS, optionsGPS);
    if (hasLocationPermission) {
      setWatchId(
        Geolocation.watchPosition(
          (position) => {
            setUserPosition({
              latitude: position.coords.latitude,
              longitude: position.coords.longitude,
            });
          },
          (error) => {
            console.log(error.code, error.message);
          },
          {
            interval: 5000,
            distanceFilter: 0,
            enableHighAccuracy: true,
            timeout: 15000,
            maximiumAge: 30000,
            showLocationDialog: true,
            forceRequestLocation: true,
          },
        ),
      );
    }
  }, [hasLocationPermission]);
```
set state position lat , lon when new position is found.
```

async function updateRequestPosition(id) {
    setTimeout(async function () {
      console.log(userPosition);
      await Geolocation.getCurrentPosition(
        (position) => {
          console.log(position);
          if (position.coords.latitude && position.coords.longitude) {
            socket.emit(
              'updateRequest',
              id,
              position.coords.latitude,
              position.coords.longitude,
              (status) => {
                // console.log('Sucesso');
                RNToasty.Success({
                  title: 'GPS Enviado com Sucesso! ',
                });
                setLoading(false);
                // console.log(status);
              },
            );
            return;
          } else {
            updateRequestPosition(id);
          }
        },
        (error) => {
          console.log(error.code, error.message);
        },
      );
    }, 5000);
```

do await updateRequestPosition inside your background action task, and you will retrieve gps data real time. Don't need to do anything else.

**Comment by PuskyWasTaken** [comment]
@samuk190 I am trying to do the same (get background coordinates) but my background task keeps getting killed when I start it. Would you be willing to share some more info? Thank you
