### ISSUE TITLE
[Question] Is this lib work with socket io [&&] legal with App Store and google play when I upload the app?

### ISSUE THREAD

**Issue by oosam2** [Rapsssito/react-native-background-actions#30]
Hello

[app description]
A program for the driver that connects to the server via the socket and sends the current location until arrive to destination
after that stop the background-actions

____________________________________________________________________________________________________________________
[problem]
-Does Google Play and App Store Rules conflict with [react-native-background-actions] and websocket?

-I am afraid of using this library because the whole app is running in the background
Once again with Rules Google Play and App Store

-the big problem it is I am new user with android and react native   XD

Thank U

**Comment by Rapsssito** [comment]
@oosam2, the only way to really know if your app will be approved is to send it for approval. However, as long as you don't violate any of the terms, it should be all right. `react-native-background-actions` does not conflict with the Google Play and App Store Rules by itself, it depends on how you use it.
