### ISSUE TITLE
[Question] Use with "react-native-track-player"

### ISSUE THREAD

**Issue by Rapsssito** [Rapsssito/react-native-background-actions#31]
Thanks for this great library! You comment about of  "react-native-track-player", but  i dont see any example with this two library  together.  do you have idea how implement? Thanks

_Originally posted by @robertfernanV in https://github.com/Rapsssito/react-native-background-actions/issues/8#issuecomment-668977859_

**Comment by Rapsssito** [comment]
@robertfernanV, this example might help you:
```js
/**
 * It must be called before the app is in the background so it can register the event listener.
 */
const backgroundTask = async () => {
    await new Promise((resolve) => {
        // Playing listeners
        const listenerChange = TrackPlayer.addEventListener('playback-state', (newState) => {
            // Do stuff
            if (newState.state === TrackPlayer.STATE_PLAYING) {
                // Play button
            } else if (newState.state === TrackPlayer.STATE_PAUSED) {
                // Pause button
            }
        });
    });
};
```

**Comment by robertfernanV** [comment]
@Rapsssito  thanks for asking! i going to try it.

**Comment by ntvinhit** [comment]
Hi @robertfernanV and @Rapsssito 

Will Apple reject this because we are using the dirty trick to "trick" Apple device?

**Comment by Rapsssito** [comment]
@ntvinhit, this will indeed result in a rejection if audio is not necessary for the app. However, the question is about an example code with "react-native-track-player", use it at your own risk.
