### ISSUE TITLE
[Android] Make the notification clickable

### ISSUE THREAD

**Issue by uptotec** [Rapsssito/react-native-background-actions#33]

**Comment by Rapsssito** [comment]
@uptotec, could you elaborate on what you want from the notification to be clickable? I guess you are referring to Android only. You mean you want to app to be opened when clicked?

**Comment by uptotec** [comment]
Yup, it would be great it if there is an option to do stuff when the notification is clicked on Android like opening the app, open a specific screen or run a function.

**Comment by Rapsssito** [comment]
@uptotec, I like the idea. However, as it is not cross-platform it won't be a top priority. **I will check what I can do**.

**Comment by uptotec** [comment]
Hey @Rapsssito , Is there any updates on this issue coming later ?

**Comment by Rapsssito** [comment]
I will be working on this for the next days. I will update this issue with new information as soon as I have it.

**Comment by Rapsssito** [comment]
@uptotec, it is released! Take a look at the [documentation](https://github.com/Rapsssito/react-native-background-actions#deep-linking) for information about how to use it.
