### ISSUE TITLE
null is not an object (evaluating '_RNBackgroundActionsModule.default.start')

### ISSUE THREAD

**Issue by PuskyWasTaken** [Rapsssito/react-native-background-actions#34]
I tried running your example but I get the bellow error when I'm trying to start the backgroud action:

Unhandled promise rejection on start
TypeError: null is not an object ( evaluating
'_RNBackgroundActionsModule.default.start')

Any ideas of how I can solve this?
Suggestion: could you maybe add a more detailed example inside the doc?

**Comment by Rapsssito** [comment]
@PuskyWasTaken, sorry you have this issue.
After installation, make sure to clean your build folder for iOS or run `./gradlew clean` for Android.

**Comment by PuskyWasTaken** [comment]
I tried everything mentioned in #21 
I also tried ```./gradlew clean``` but with no success.

![image](https://user-images.githubusercontent.com/49597849/91430667-ea653c00-e867-11ea-9465-41b310d2e3e0.png)

**Comment by Rapsssito** [comment]
@PuskyWasTaken, could you provide the code that is causing the error?

**Comment by PuskyWasTaken** [comment]
I did try resetting the cache.

The code:

## First, I am using exactly the example code provided.
```javascript
import BackgroundService from 'react-native-background-actions';

// You can do anything in your task such as network requests, timers and so on,
// as long as it doesn't touch UI. Once your task completes (i.e. the promise is resolved),
// React Native will go into "paused" mode (unless there are other tasks running,
// or there is a foreground app).

let heartBeat = false;
const veryIntensiveTask = async (taskDataArguments) => {
    // Example of an infinite loop task
    const { delay } = taskDataArguments;
    await new Promise(async (resolve) => {
        for (let i = 0; BackgroundService.isRunning(); i++) {
            console.log(i);
            heartBeat = !heartBeat;
            await sleep(delay);
        }
    });
};

const options = {
    taskName: 'Example',
    taskTitle: 'ExampleTask title',
    taskDesc: 'ExampleTask desc',
    taskIcon: {
        name: 'ic_launcher',
        type: 'mipmap',
    },
    color: '#ff00ff',
    parameters: {
        delay: 1000,
    },
};
```

## Here is the call
```javascript
const HeartbeatClass = () => {
  const imageSize = heartBeat ? 150 : 100;

  React.useEffect(() => {
    const startBackgroundService = async () => {
        await BackgroundService.start(veryIntensiveTask, options)
    };
    startBackgroundService();
  }, []);


  return (
    <View style={styles.container}>
      <View style={styles.view}>
        <Image source={heart} style={{ width: imageSize, height: imageSize }} resizeMode="contain" />
      </View>
      <View style={styles.view}>
      </View>
    </View>
  );
};
```

**Comment by Rapsssito** [comment]
@PuskyWasTaken, it looks like an error on the link between the React Native and the module. Could you try to remove and add the library?
`yarn remove react-native-background-actions`
`yarn add react-native-background-actions`

And then post your package.json?

**Comment by PuskyWasTaken** [comment]
I did @Rapsssito.
Below is the package.json (changed extension to .txt so I can upload it) 
[package.txt](https://github.com/Rapsssito/react-native-background-actions/files/5135910/package.txt)

**Comment by Rapsssito** [comment]
@PuskyWasTaken, are you on iOS or Android?

**Comment by PuskyWasTaken** [comment]
Android

**Comment by Rapsssito** [comment]
@PuskyWasTaken, could you try to run the app from Android Studio and check if are still having the issue?

**Comment by PuskyWasTaken** [comment]
@Rapsssito I will, in a few minutes

**Comment by PuskyWasTaken** [comment]
@Rapsssito After a whole day of debugging it not works but for the love of GOD..I don't know why. Thank you for the help and quick responses anyway!

For future people that might read this..good luck
