### ISSUE TITLE
What happens when the task finishes?

### ISSUE THREAD

**Issue by brunocrocomo** [Rapsssito/react-native-background-actions#35]
Hello!

First of all, thanks for this great library! 

Currently i'm using it to keep my application running while downloading some big files and it works very well. Altough, I've noticed something and I'd like to ask what is really happening. 

Just to begin to explain it, I use [Reactotron](https://github.com/infinitered/reactotron) to inspect my application. When the task finishes while the application is _closed_ - calling `resolve()` inside a _Promise_ or forcing it to stop with `BackgroundService.stop()` - the notification is gone but it is still possible to notice that the application is still running and connected to Reactotron. If I try to re-open the application, it's not "really re-launched" and it acts like it was already opened. It's also possible to notice that some Redux actions are not _dispatched_ (like the `persist/rehydrate` from [redux-persist](https://github.com/rt2zz/redux-persist)) as they should be on the application launch.

In the [documentation](https://github.com/Rapsssito/react-native-background-actions) it says that **once your task completes (i.e. the promise is resolved), React Native will go into "paused" mode (unless there are other tasks running, or there is a foreground app)**. This means that the application is kept opened, even if the task is finished or `BackgroundService.stop()` was called?

**Comment by Rapsssito** [comment]
@brunocrocomo, thanks for the feedback! **I didn't know about Reactotron, but it looks like a very useful library**. Sadly, I cannot answer why the application is still running and connected to Reactotron because I don't know how it works.

> In the documentation it says that once your task completes (i.e. the promise is resolved), React Native will go into "paused" mode (unless there are other tasks running, or there is a foreground app). This means that the application is kept opened, even if the task is finished or BackgroundService.stop() was called?

That part of the Android documentation is directly taken from [React Native HeadlessJS documentation](https://reactnative.dev/docs/headless-js-android.html#the-js-api). It's not the best documentation in the world, really. However, they say _**"paused" mode**_, which does not mean "closed". **As far as I know, you might have found a bug in `com.facebook.react.HeadlessJsTaskService` class**. I don't know how the `HeadlessJsTaskService` is implemented, only that it extends [`android.app.Service`](https://developer.android.com/reference/android/app/Service) abstract class.

If I had to guess, I would say that the application is not being closed because the JavaScript engine is still running (_maybe doing garbage collection or other task under the hood_), even if your task is completed.

**Comment by brunocrocomo** [comment]
Hi, @Rapsssito! Thanks for the answer! For React Native < 0.62 I always use Reactotron and for React Native >= 0.62 I use [Flipper](https://fbflipper.com/docs/getting-started/react-native). They're both great tools, indeed! 

Talking about, I'll setup a project from scratch (with React Native > 0.62) and inspect with Flipper just to see what happens.

> That part of the Android documentation is directly taken from React Native HeadlessJS documentation. It's not the best documentation in the world, really. However, they say "paused" mode, which does not mean "closed". As far as I know, you might have found a bug in com.facebook.react.HeadlessJsTaskService class. I don't know how the HeadlessJsTaskService is implemented, only that it extends android.app.Service abstract class.
>
> If I had to guess, I would say that the application is not being closed because the JavaScript engine is still running (maybe doing garbage collection or other task under the hood), even if your task is completed.

That makes sense. I'll investigate further more and get back with the results!

**Comment by brunocrocomo** [comment]
Hello again!

I spent some time testing different things just to make sure I wasn't doing anything wrong. For example, I tested some different values ​​for `android:launchMode` in the `AndroidManifest.xml`, but I always got the same result. As soon as possible I will observe the behavior on iOS (using the `react-native-track-player` or something else, as explained in the documentation).

On this test, I created an application from scratch with **React Native 0.63.2** and inspected it using **Flipper**. I let a single task running in the background for a few seconds before finishing it. The code is below:

```
const handleOnPress = () => {
    BackgroundService.start(
        async () => {
            await new Promise(async resolve => {
                const sleep = time =>
                    new Promise(r => setTimeout(() => r(), time));

                let count = 0;
                while (count < 10) {
                    count += 1;
                    console.log(`Background task count: ${count}`);

                    await sleep(1000);
                }

                console.log('Task finished!');

                resolve();
            });
        },
        {
            taskName: 'Example',
            taskTitle: 'ExampleTask title',
            taskDesc: 'ExampleTask desc',
            taskIcon: {
                name: 'ic_launcher',
                type: 'mipmap',
            },
            color: '#ff00ff',
            parameters: {
                delay: 1000,
            },
        },
    );
};
```

Also, I used the [AppState API](https://reactnative.dev/docs/appstate) to observe how the application would behave while opening and closing it. The code is pretty much the example shown in `AppState` documentation:

```
const appState = useRef(AppState.currentState);

const handleAppStateChange = nextAppState => {
    if (
        appState.current.match(/inactive|background/) &&
        nextAppState === 'active'
    ) {
        console.log('App has come to the foreground!');
    }

    appState.current = nextAppState;
    console.log('AppState', appState.current);
};

useEffect(() => {
    AppState.addEventListener('change', handleAppStateChange);

    return () => {
        AppState.removeEventListener('change', handleAppStateChange);
    };
}, []);
```
The log of the application running is shown below:

```
18:17:38.129	bundle_build_started
18:17:38.148	bundle_build_done
18:17:39.450	client_log		Running "TestApp" with {"rootTag":1} // Here I opened the application for the first time (notice that the bundle was built and the rootTag is 1) 
18:17:39.450	client_log		AppState active
18:17:43.235	client_log		Background task count: 1
18:17:46.116	client_log		Background task count: 2
18:17:46.116	client_log		AppState background // Here I closed the application and let the task running in background
18:17:46.117	client_log		Background task count: 3
18:17:46.273	client_log		Background task count: 4
18:17:47.311	client_log		Background task count: 5
18:17:50.136	client_log		Background task count: 6
18:17:50.139	client_log		Background task count: 7
18:17:50.373	client_log		Background task count: 8
18:17:51.404	client_log		Background task count: 9
18:17:54.166	client_log		Background task count: 10
18:17:54.172	client_log		Task finished!
18:17:58.219	client_log		Running "TestApp" with {"rootTag":21} // Here I opened the application (notice that the bundle wasn't built and the rootTag is 21) 
18:17:58.221	client_log		App has come to the foreground!
18:17:58.222	client_log		AppState active
18:18:07.961	client_log		Background task count: 1
18:18:10.294	client_log		Background task count: 2
18:18:10.299	client_log		Background task count: 3
18:18:11.014	client_log		Background task count: 4
18:18:12.007	client_log		AppState background // Here I closed the application again and let another task running in background
18:18:12.030	client_log		Background task count: 5
18:18:14.326	client_log		Background task count: 6
18:18:14.332	client_log		Background task count: 7
18:18:15.074	client_log		Background task count: 8
18:18:16.105	client_log		Background task count: 9
18:18:18.357	client_log		Background task count: 10
18:18:18.358	client_log		Task finished!
18:18:26.548	client_log		Running "TestApp" with {"rootTag":31} // Here I opened the application again (notice that the bundle wasn't built again and the rootTag is 31) 
18:18:26.550	client_log		App has come to the foreground!
18:18:26.550	client_log		AppState active
18:18:34.598	client_log		AppState background // Here I closed the application without a task running in background
18:18:42.500	bundle_build_started	
18:18:42.505	bundle_build_done
18:18:43.800	client_log		Running "TestApp" with {"rootTag":1} // Here I opened the application again (notice that the bundle was built and the rootTag is 1) 
18:18:43.800	client_log		AppState active
```

**It's interesting to notice that every time that I opened the application after the background task finished, the rootTag got incremented by 10. It's also possible to notice that the application behave like it was in background and came to the foreground when it prints "App has come to the foreground!" into the log.** 

This same behavior is possible to reproduce opening the application and closing it with the Android "back button". If I open the application again, it's also possible to notice the rootTag being incremented by 10 and the log "App has come to the foreground!". This is even crazier because it has no connection with the background tasks hahaha.

Maybe I'm completely wrong, but **I believe that this "paused state" is exactly this**: the application "hangs" like it was put on background (not closed) and, when it's opened, fires the JS thread where it was when the application was "paused". 

My main concern about this is the battery usage. As far I observed, the application is not **really** running in this weird state (closed, but not really) so I think this is not a real problem.

If I discover anything else I'll get in touch. Thank you for your attention and thank you again for this amazing library!

**Comment by brunocrocomo** [comment]
@Rapsssito Oh, that makes sense and it's good to know. I was a little paranoid about this battery matter hahaha.

The log I provided was obtained when the `AndroidManifest.xml` activity was set to `android:launchMode="singleTask"` (it's the default launchMode when the project is setup from scratch, if I'm not wrong). 

Would you like me to test with another values?

**Comment by Rapsssito** [comment]
@brunocrocomo, you are right! I forgot React Native 0.62 changed `android:launchMode` to `"singleTask"`. Then, no more testing is necessary. As you said, _this same behavior is possible to reproduce opening the application and closing it with the Android "back button"_, so this "issue" **might have more to do with React Native itself, rather than react-native-background-actions**.

**Comment by brunocrocomo** [comment]
@Rapsssito Alright! 

Yup, I agree with you, this is probably related to the way the React Native works. 

For now, everything is working as expected and I just wanted to make sure that I wasn't doing anything wrong or weird with the background tasks.

Thank you once more!

**Comment by rewhex** [comment]
Hello there, I've resolved this "issue" with react-native-exit-app, calling RNExitApp.exitApp() will kill both background service and main process, also you don't need to call .stop() or resolve() for background service.

**Comment by brunocrocomo** [comment]
Hey @rewhex! Thanks for the tip!

I will inform my team about this library!

Just for the record, during that time we didn't notice any problems with the application in the "paused state" and everything worked as explained by @Rapsssito.
