### ISSUE TITLE
[Android] Modify notification

### ISSUE THREAD

**Issue by ibnekhan** [Rapsssito/react-native-background-actions#36]
How can we update notification. If we want to show some processing percentage or progress bar into notification. How can we do that??

**Comment by Rapsssito** [comment]
@ibnekhan, currently it is not possible. However, I plan adding it in the near future. I will update this issue when it is available!

**Comment by ibnekhan** [comment]
@Rapsssito would you update in days or it would take weeks to release this modification?

**Comment by Rapsssito** [comment]
@ibnekhan, I will start working on it now. I might have something for tomorrow.

**Comment by Rapsssito** [comment]
You can check the [`Usage` documentation](https://github.com/Rapsssito/react-native-background-actions#usage) for how to update your notification!

**Comment by ibnekhan** [comment]
@Rapsssito Nice and speedy work man 👍 But progress update part is missing.

**Comment by Rapsssito** [comment]
@ibnekhan, could you create another issue with that request? That way I can organize myself a little better.
