### ISSUE TITLE
[Android] Notification icon is not showing

### ISSUE THREAD

**Issue by Great-hijack** [Rapsssito/react-native-background-actions#38]
@Rapsssito Thanks for great library!
I decided to use this library for my app, but I just faced a issue.
Looking forward to get solved this issue. 

![image](https://user-images.githubusercontent.com/57619523/92118106-9b4f7600-ee28-11ea-859e-95748ec39c5c.png)

![image](https://user-images.githubusercontent.com/57619523/92118766-7f000900-ee29-11ea-90cb-fefaf9624008.png)

```
        const options = {
          taskName: 'location-tracking',
          taskTitle: 'You are on shift',
          taskDesc: 'RRA is tracking your location',
          taskIcon: {
            name: 'ic_launcher',
            type: 'mipmap',
          },
          color: '#ff00ff',
          parameters: {
            delay: 1000,
          },
        };
```

**Comment by Rapsssito** [comment]
@Great-hijack, could you provide the correct icon so I can test it?

**Comment by Great-hijack** [comment]
I generated the app icon by using Android Studio.
I think the icon is not a problem.
Btw, I attached the icons [mipmap-hdpi.zip](https://github.com/Rapsssito/react-native-background-actions/files/5169835/mipmap-hdpi.zip)

**Comment by Rapsssito** [comment]
@Great-hijack, the issue is caused by your icon. **The notification icon background must be transparent** so Android can display it correctly, yours is actually #fdf1fa.

**Comment by Qurat-ul-ainn** [comment]
i have same issue not a single solution work for me
[mipmap-hdpi 2.zip](https://github.com/user-attachments/files/17506720/mipmap-hdpi.2.zip)
this is my icon folder.
