### ISSUE TITLE
How to keep the task running without infinite loop

### ISSUE THREAD

**Issue by uptotec** [Rapsssito/react-native-background-actions#42]
Hello,
my target is to keep multiple event listeners working in the background. my question is How to keep the task running with the event listeners in the background without an infinite loop.
I tried to do the code below and I works but then I observed that the app drains a lot of battery and I guess that the infinite loop for a along period of time is a contributor to the battery drain.
I'll appreciate your help.
```typescript

/**
 * event listeners here
 */

function sleep(ms: number) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

while (true) {
    await sleep(5000);
  }
```

**Comment by Rapsssito** [comment]
@uptotec, a `while(true)` is never a good options because the CPU is constantly executing instructions. One way to keep the task running would be never resolving the promise:
```js
const veryIntensiveTask = async (taskDataArguments) => {
    // Example of an infinite task
    await new Promise(() => {
        // Do things, this promise will never resolve
    });
};
```
