### ISSUE TITLE
Persist background task after restart

### ISSUE THREAD

**Issue by c7nasr** [Rapsssito/react-native-background-actions#43]
Can you add presist after restarting mobile functionality?

**Comment by Rapsssito** [comment]
@c7nasr, I have marked this issue as an enhancement. I will start working on it ASAP.

**Comment by c7nasr** [comment]
That's would be great.!!

**Comment by roysG** [comment]
Yes this totally will be awsome!

**Comment by danielfigueroaj** [comment]
Any updates about this new feature? Thanks for your awesome work

**Comment by Rapsssito** [comment]
@danielfigueroaj It looks like it might not be possible since you cannot save the JavaScript code reference from the AppRegistry to any persistent storage.

**Comment by danielfigueroaj** [comment]
@Rapsssito For Android... what if a RECEIVE_BOOT_COMPLETED is implemented and using a Broadcast Receiver, just try to run the RNBackgroundActionsTask service?

**Comment by Rapsssito** [comment]
@danielfigueroaj that's what I have been doing, but that's not the problem. The problem is to call from the bridge the JavaScript function that was running before the device was turned off.

**Comment by harshadghoghari84** [comment]
@Rapsssito I can't open app from notification , any solution ?

**Comment by danielfigueroaj** [comment]
Did you configure the deep linking?

**Comment by Rapsssito** [comment]
It looks like this enhancement is not possible to implement in the current state of React Native. I find it impossible to store the current state of the JavaScript engine and unable to start the background task on startup on Android or iOS.
