### ISSUE TITLE
How to check if task has already been created

### ISSUE THREAD

**Issue by hp040** [Rapsssito/react-native-background-actions#44]
first of all, thank you for this package, 

I want to create a task only if the task not running already (uniquely identify tasks)

**Comment by Rapsssito** [comment]
@hp040, you may use `BackgroundService.isRunning(): boolean` (more info [here](https://github.com/Rapsssito/react-native-background-actions/blob/master/lib/types/index.d.ts)):

```js
if (!BackgroundService.isRunning()) {
    BackgroundService.start(veryIntensiveTask, options);
}
```

**Comment by hp040** [comment]
got it thanks buddy
