### ISSUE TITLE
How to start the service every 5 minutes regardless of app state

### ISSUE THREAD

**Issue by tauqeer81** [Rapsssito/react-native-background-actions#47]
I want to start the service every 5 minutes to check for any offline data in Async Storage even if the app is closed or in background state. If there's any data available in storage then it should upload the offline data to server and stops the service. I haven't seen any example in the documentation. The service should start every 5 minutes in both android and ios.

**Comment by Rapsssito** [comment]
@tauqeer81, you could use `setInterval()` inside the BackgroundTask. However, timers do not always behave as expected when the app is in the background ([more info](https://reactnative.dev/docs/headless-js-android.html#caveats)). Here is an example:
```js
const task = async (taskDataArguments) => {
    // Example of an interval task
    const { delay } = taskDataArguments;
    await new Promise(() => { // Never resolve
        setInterval(() => {
           // Your AsyncStorage stuff
        }, delay);
    });
};
```

**Comment by nguyenanhthai** [comment]
@Rapsssito How can I clear the interval in this case?

**Comment by joseortiz9** [comment]
@Rapsssito Please indicate how to clean the intervals please

**Comment by Rapsssito** [comment]
@nguyenanhthai, @joseortiz9, you can use the classic: `clearInterval()`.
