### ISSUE TITLE
[Question] Is it possible to run a custom hook inside the function on BackgroundService.start?

### ISSUE THREAD

**Issue by EmmanuelJh** [Rapsssito/react-native-background-actions#48]
for example: 

const myTask = () -> {
  const { something } = useMyCustomHook()
await something()
}

await BackgroundService.start(veryIntensiveTask, options)

**Comment by Rapsssito** [comment]
@EmmanuelJh, it might be possible. However, you have to make sure it does not affect your UI. You can read more about it [here](https://reactnative.dev/docs/headless-js-android.html#the-js-api):

> You can do anything in your task such as network requests, timers and so on, **as long as it doesn't touch UI** (...)
