### ISSUE TITLE
Prevent hibernation with background activities

### ISSUE THREAD

**Issue by duarte-evocorp** [Rapsssito/react-native-background-actions#54]
How to prevent the cell phone from hibernating with background activities?

**Comment by Rapsssito** [comment]
@duarte-evocorp are you on iOS or Android?

**Comment by duarte-evocorp** [comment]
Android

**Comment by Rapsssito** [comment]
@duarte-evocorp what do you mean by hibernation? You mean the screen going to the lock scren if the user is not using the device?

**Comment by duarte-evocorp** [comment]
This, I want the application when it is open to prevent the screen from turning off. This is already happening, but when he puts the app in the background a few minutes later he hangs up.

**Comment by duarte-evocorp** [comment]
I want the screen to remain on even in the background.

**Comment by Rapsssito** [comment]
@duarte-evocorp sorry, but that is not possible currently on Android.

**Comment by duarte-evocorp** [comment]
I understand, thank you.
