### ISSUE TITLE
taskIcon seems not to have any effect when the app icon (ic_launcher in my case) is used 

### ISSUE THREAD

**Issue by AnagramEngineering** [Rapsssito/react-native-background-actions#55]
There's not much description on this topic, besides the sample. 

Also the screenshot in the documentation shows a square white icon in the status bar (placeholder for the notification)

Should that work (e.g. creating a separate icon with the correct formatting?)

**Comment by AnagramEngineering** [comment]
My assumption was right, it's not possible to use the default appicon but a separate task icon is required. Once this is provided, it's correctly displayed. 

Great, thx for your work!

**Comment by Qurat-ul-ainn** [comment]
> My assumption was right, it's not possible to use the default appicon but a separate task icon is required. Once this is provided, it's correctly displayed.
> 
> Great, thx for your work!



> My assumption was right, it's not possible to use the default appicon but a separate task icon is required. Once this is provided, it's correctly displayed.
> 
> Great, thx for your work!

in which folder this separate icon have to put with what name ? please explain
