### ISSUE TITLE
Is it possible to update data from main UI thread -> already running background task?

### ISSUE THREAD

**Issue by act-naturally** [Rapsssito/react-native-background-actions#57]
Hi, 

Thanks a lot for creating this library first of all. 

I have an app that records a user's heart rate and monitors our some statistics. I would like this monitoring to continue even when the user minimizes the application, which is why I have started looking into Headless JS and your library. Right now, I can start up a background task using your library and read HR data continuously whether the app is on the foreground or not, which is great. I can also update main thread UI state from my background task ( I pass in a function to options), to keep a log of these measurements which is also good. (communication from running background task -> main UI thread)

My main issue right now is that I would like to send some data to the active background task  ( communication from Main thread to running background task) and I am unable to do so.  I have tried doing this by passing a piece of useState from my main UI thread when I initialize the background job on startup via:

BackgroundJob.start(taskRandom, options)

The issue I'm experiencing is that if I update this state within my main UI thread, this does not get reflected on the current background task. Is this expected or am I doing something wrong?

**Comment by Rapsssito** [comment]
@act-naturally, you could pass a reference to an already instantiated event emitter. For example:

```js
const uiEventEmitter = new EventEmitter();

const task = async (taskDataArguments) => {
    await new Promise(() => {
           uiEventEmitter.addEventListener('event', () => {
              // Your UI wanted to change something
           };
           // Listen to hear rate
    });
};

// UI
BackgroundJob.start(task, options);
// Do stuff
// Emit the event with the info you want to communicate
uiEventEmitter.emit('event');
```

**Comment by act-naturally** [comment]
Great, this is perfect. I couldn't use EventEmitter but DeviceEventEmitter did work for me for anyone interested: 

```js
import { DeviceEventEmitter} from 'react-native';

const task = async (taskDataArguments) => {
    await new Promise(() => {
        // background thread
 DeviceEventEmitter.addListener('event.test', (event) => {
                // do something with event from UI
            });
    });
};

// UI
BackgroundJob.start(task, options);
// Do stuff
// Emit the event with the info you want to communicate
 DeviceEventEmitter.emit('event.test', { anyEventProps.. })
```
`
