### ISSUE TITLE
unable to open file (in target "RNBackgroundActions" in project "RNBackgroundActions")

### ISSUE THREAD

**Issue by maihonganh1997** [Rapsssito/react-native-background-actions#59]
After installing the package, I got an error on IOS

Showing Recent Messages
project/node_modules/react-native-background-actions/ios/Pods/Target Support Files/Pods-RNBackgroundActions/Pods-RNBackgroundActions.debug.xcconfig: unable to open file (in target "RNBackgroundActions" in project "RNBackgroundActions")

I'm using react-native-background-actions: 2.5.2 and react-native: 0.59.9

How to fix it?

Thanks,

**Comment by Rapsssito** [comment]
@maihonganh1997, could you try again after cleaning your XCode build cache?

**Comment by maihonganh1997** [comment]
@Rapsssito I tried cleaning XCode build-cache but still got the old error

**Comment by maihonganh1997** [comment]
Then, I tried "cd ios && pod install && cd .." and got another error

[!] Unable to find a specification for `React-Core` depended upon by `react-native-background-actions`

You have either:
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

**Comment by Rapsssito** [comment]
@maihonganh1997, it might be a problem with RN 0.59.9 and React-Core pod. Could you try react-native-background-actions@2.5.0?

**Comment by maihonganh1997** [comment]
I tried react-native-background-actions@2.5.0, but still got the error:

[!] Unable to find a specification for `React-Core` depended upon by `react-native-background-actions`

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

**Comment by Rapsssito** [comment]
@maihonganh1997, react-native-background-actions@2.5.0 does not depend on `React-Core`. Make sure you update your pod files after downgrading and clean all your caches.

**Comment by maihonganh1997** [comment]
I downgraded react-native-background-actions@2.5.0 and cleared the caches on my mac but I still got the old error :(

**Comment by maihonganh1997** [comment]
I created a test project with version: 0.63.3 and installed react-native-background-action package, it does work, :)

**Comment by maihonganh1997** [comment]
I also got another error for the old project 0.59.9 when I installed the package:
YellowBox.js:67 Possible Unhandled Promise Rejection (id: 0):
TypeError: Cannot read property 'start' of undefined
TypeError: Cannot read property 'start' of undefined
    at BackgroundServer.start$ (blob:http://localhost:8081/59e5131c-0046-4b96-b58f-41459f84558c:104967:86)
    at tryCatch (blob:http://localhost:8081/59e5131c-0046-4b96-b58f-41459f84558c:25954:19)
    at Generator.invoke [as _invoke] (blob:http://localhost:8081/59e5131c-0046-4b96-b58f-41459f84558c:26129:24)
    at Generator.prototype.<computed> [as next] (blob:http://localhost:8081/59e5131c-0046-4b96-b58f-41459f84558c:25997:23)
    at tryCatch (blob:http://localhost:8081/59e5131c-0046-4b96-b58f-41459f84558c:25954:19)
    at invoke (blob:http://localhost:8081/59e5131c-0046-4b96-b58f-41459f84558c:26030:22)
    at blob:http://localhost:8081/59e5131c-0046-4b96-b58f-41459f84558c:26060:13
    at tryCallTwo (blob:http://localhost:8081/59e5131c-0046-4b96-b58f-41459f84558c:3185:7)
    at doResolve (blob:http://localhost:8081/59e5131c-0046-4b96-b58f-41459f84558c:3349:15)
    at new Promise (blob:http://localhost:8081/59e5131c-0046-4b96-b58f-41459f84558c:3208:5)

Bed like the package has a problem with rn: 0.59.9

**Comment by Rapsssito** [comment]
@maihonganh1997 that error looks like a failed linking between React Native and `react-native-background-actions`. It might be a problem with your particular RN 0.59.9 setup and linking, it is a common issue with React Native libraries. Take a look at my comment on this thread https://github.com/Rapsssito/react-native-tcp-socket/issues/27#issuecomment-616163678
