### ISSUE TITLE
Abilty to stop task on app close on Android

### ISSUE THREAD

**Issue by rlebosse** [Rapsssito/react-native-background-actions#62]
Hello, I would like to be able to stop the task when the main activity is stopped (for removed from the app drawer).

Is there a way to do so ? In the JS Code of React Native or maybe in some native Android code ?

Thanks in advance and keep the good work !

Romain

**Comment by Rapsssito** [comment]
@rlebosse, here is an example:
```js
componentWillUnmount() {
        BackgroundService.stop();
}
```

You could write that code on the App.js file or any other component you want.

**Comment by rlebosse** [comment]
It works like a charm, thanks @Rapsssito !
