### ISSUE TITLE
[ Task icon not found ]

### ISSUE THREAD

**Issue by Raul-Coelho** [Rapsssito/react-native-background-actions#63]
When I try to change the name of the return icon with this problem. All icons are PNG and they all exist.

**Comment by Rapsssito** [comment]
@Raul-Coelho, make sure to place your icons in the correct `/res` folder. I highly recommend you to use Android Studio for icon management.

**Comment by Joshmatjjen** [comment]
Same issue here

**Comment by Rapsssito** [comment]
@Joshmatjjen, have you set up your icons using Android Studio?

**Comment by Joshmatjjen** [comment]
@Repssito It is fixed now... My icon had a background...

**Comment by Qurat-ul-ainn** [comment]
I have same issue any souluntion? my icon is in the right folder and haven't background.
