### ISSUE TITLE
how to show smallicon in statusbar?

### ISSUE THREAD

**Issue by jafarpishdadi** [Rapsssito/react-native-background-actions#64]
thanks
I want to write a weather app
I used your package ... very good
How do I show a small icon in the phone status bar?

**Comment by Rapsssito** [comment]
@jafarpishdadi, if you want to add a task icon take a look at the [documentation](https://github.com/Rapsssito/react-native-background-actions/blob/master/USAGE.md#options), more precisely the `taskIcon` option.

**Comment by jafarpishdadi** [comment]
thanks 
task icon show but not show in statusbar 
Looks like this photo
![image](https://user-images.githubusercontent.com/11630480/103394142-f45fba00-4b3b-11eb-947e-157341639ac7.png)
