### ISSUE TITLE
Background Task Remove/Kill Automatically For some conditions

### ISSUE THREAD

**Issue by iamamanprajapati** [Rapsssito/react-native-background-actions#65]
Background task removes/kill when I closed all applications at a time with android's "Closed All" button.

**Comment by iamamanprajapati** [comment]
https://user-images.githubusercontent.com/49456931/103453568-6a614e00-4d01-11eb-87a1-599cc277c7cb.mp4

#Video

**Comment by Rapsssito** [comment]
@iamamanprajapati, your problem might not be fixable. If you remove an app from the background all the background tasks created from that app become a target to be removed. You can read more about it in #26.

**Comment by iamamanprajapati** [comment]
What can I do about this problem?

**Comment by Rapsssito** [comment]
@iamamanprajapati, I don't know your exact use case, but you might need to create your own native module for your exact necessities.

**Comment by iamamanprajapati** [comment]
Thanks !!
