### ISSUE TITLE
Notification badge icon not showing in the top of android notification bar

### ISSUE THREAD

**Issue by Joshmatjjen** [Rapsssito/react-native-background-actions#66]
Please can we add the .setBadgeIconType Top view Notification icon on android

**Comment by Joshmatjjen** [comment]
![message-3062306-15820421661767275707](https://user-images.githubusercontent.com/32624413/104249271-6228b180-546b-11eb-97b3-cd8ffd30664b.jpeg)

**Comment by Rapsssito** [comment]
@Joshmatjjen, thanks for the feedback! Unfortunately, I cannot add this feature because using `setBadgeIconType()` would require to bump the Android's `MIN_SDK_VERSION` from 21 to 26. This would reduce backwards compatibility and induce a BREAKING CHANGE in the library.

**Comment by Joshmatjjen** [comment]
@Rapsssito  I am using a Libary called "react-native-music-control", Icon show always and MIN_SDK_VERSION is 16

**Comment by Rapsssito** [comment]
@Joshmatjjen, music icons are supported since much earlier. Take a look at the [docs](https://developer.android.com/reference/android/app/Notification.Builder#setBadgeIconType(int)) for more info.
