### ISSUE TITLE
How To Remove Notification Bar When App Is Terminated

### ISSUE THREAD

**Issue by Umair115** [Rapsssito/react-native-background-actions#67]
Hello there guys, I hope you guys are doing fine, i am using this amazing package for background processes and every thing is working amazing but there is one issue which i am facing is the notification bar which is continuously there even when the app is terminated, i dont want that bar, when i am trying to remove that bar by modifying the package, app stops working in the terminated mode. Someone please suggest something regarding this issue!
Thanks In Advance

**Comment by Rapsssito** [comment]
@Umair115 the notification shows even when the app is terminated because the background job is still running. Take a look at #62 in order to check out how to stop the background task when the main activity is killed.

**Comment by Umair115** [comment]
i dont want to kill the task, i just want to remove that notification bar, also that notification bar automatically disappears after half an hour or so, then the task stops working. i want the to continously work, it is some sort of alarm application, so the task needs to work continously but i dont want the notification bar to appear

**Comment by Rapsssito** [comment]
@Umair115, I am sorry but the notification must always be displayed to the user. Take a look at #56.

**Comment by my4fdal** [comment]
Sorry, bro, so the point is that this library can't run tasks in the background when notifications are removed, bro, is there no way to get rid of it, this is what I always want to ask, hehe ✌

**Comment by GiuseppeEpifani** [comment]
> No quiero eliminar la tarea, solo quiero eliminar esa barra de notificaciones, también esa barra de notificaciones desaparece automáticamente después de media hora más o menos, luego la tarea deja de funcionar. quiero que funcione continuamente, es una especie de aplicación de alarma, por lo que la tarea debe funcionar continuamente, pero no quiero que aparezca la barra de notificación

What was the solution to make your service work continuously without stopping in the background after a while? I am creating an application with functionality similar to yours that has a timer.
