### ISSUE TITLE
Possible Unhandled Promise Rejection when calling BackgroundService.updateNotification(...) and app is killed

### ISSUE THREAD

**Issue by TheStraing** [Rapsssito/react-native-background-actions#69]
Hi,
I get this error when the app is killed while the background action is running.

<img width="814" alt="Schermata 2021-02-13 alle 11 17 39" src="https://user-images.githubusercontent.com/16732179/107847579-17dd7c00-6ded-11eb-9d26-2677c8c80ef5.png">

The background task still runs fine, It's just not possible to update the notification (if I have a progress bar for example).

**Comment by Rapsssito** [comment]
@TheStraing, thanks for the feedback! This is a known issue, please check #61
