### ISSUE TITLE
how to stop backgroundservice for cleaning up 

### ISSUE THREAD

**Issue by hamidashoor98** [Rapsssito/react-native-background-actions#70]
hi this is my code and when I destroy app, the app is working 
but when i want to start the app again and stop the BackgroundService (by  await BackgroundService.stop() )  top of useEffect, the past services  doesn't stop  for cleaning up  .   

how to clean up the past services?

```
useEffect(() => {
    async function fetchData() {
      await getPermission()
      await BackgroundService.stop()

      await BackgroundService.start(veryIntensiveTask, options)

      await BackgroundService.updateNotification({
        taskDesc: 'something'
      })
    }

    fetchData()


  }, [])
```

**Comment by Rapsssito** [comment]
@hamidashoor98, I don't really understand your issue. Is it related to #62?

**Comment by chrisdukakis** [comment]
@Rapsssito he means that `BackgroundService.stop()` doesn't work if you close and reopen the App. Services spawn by previous app instances will keep running.
