### ISSUE TITLE
[iOS] support expirationHandler

### ISSUE THREAD

**Issue by petergaultney** [Rapsssito/react-native-background-actions#72]
This is just a feature request, but it would be very helpful to me if this library supported passing a JS callback for the iOS-only expiration handler that allows you to 'clean up' for 1 second before your task is ended.

https://developer.apple.com/documentation/uikit/uiapplication/1623031-beginbackgroundtask

I am essentially incompetent as an Objective C developer, or I'd happily contribute a PR. :P

**Comment by Rapsssito** [comment]
@petergaultney thanks for the feedback! I will take a look at it and come back to you as soon as I get something.
