### ISSUE TITLE
Showing Unexpected reserved word 'await' error in App.js file

### ISSUE THREAD

**Issue by itsAkky** [Rapsssito/react-native-background-actions#73]
**Bellow is code which i have added in App.js** 
```js
import BackgroundService from 'react-native-background-actions';
import { Linking } from 'react-native';
Linking.addEventListener('url', handleOpenURL);

// You can do anything in your task such as network requests, timers and so on,
// as long as it doesn't touch UI. Once your task completes (i.e. the promise is resolved),
// React Native will go into "paused" mode (unless there are other tasks running,
// or there is a foreground app).
const veryIntensiveTask = async (taskDataArguments) => {
    // Example of an infinite loop task
    const { delay } = taskDataArguments;
    await new Promise( async (resolve) => {
        for (let i = 0; BackgroundService.isRunning(); i++) {
            console.log(i);
            await sleep(delay);
        }
    });
};


function handleOpenURL(evt) {
    // Will be called when the notification is pressed
    console.log(evt.url);
    // do something
}

const options = {
    taskName: 'Example',
    taskTitle: 'ExampleTask title',
    taskDesc: 'ExampleTask description',
    taskIcon: {
        name: 'ic_launcher',
        type: 'mipmap',
    },
    color: '#ff00ff',
    linkingURI: 'https://github.com/Rapsssito/react-native-background-actions/blob/master/USAGE.md#deep-linking', // See Deep Linking for more info
    parameters: {
        delay: 1000,
    },
};


await BackgroundService.start(veryIntensiveTask, options);
await BackgroundService.updateNotification({taskDesc: 'New ExampleTask description'}); // Only Android, iOS will ignore this call
// iOS will also run everything here in the background until .stop() is called
await BackgroundService.stop();



```
**Bellow is code which i have added in AndroidManifest.xml**

<manifest xmlns:android="http://schemas.android.com/apk/res/android"
  package="com.backrn">

    <uses-permission android:name="android.permission.INTERNET" />

    <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />

    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:roundIcon="@mipmap/ic_launcher_round"
      android:allowBackup="false"
      android:theme="@style/AppTheme">
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode"
        android:launchMode="singleTask"
        android:windowSoftInputMode="adjustResize">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>

        <intent-filter android:label="filter_react_native">
            <action android:name="android.intent.action.VIEW" />
            <category android:name="android.intent.category.DEFAULT" />
            <category android:name="android.intent.category.BROWSABLE" />
            <data android:scheme="https://github.com/Rapsssito/react-native-background-actions/blob/master/USAGE.md#deep-linking" />
        </intent-filter>
                  
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
      <service android:name="com.backrn.react.bgactions.RNBackgroundActionsTask" />
    </application>

</manifest>

I'm beginner in  React Js. I'm trying to create a app which should run in background as well. Please help me with this . Thank you in advance..

**Comment by Rapsssito** [comment]
@itsAkky, this is not a ReactJS problem, it is a vanilla JS one. You cannot use `await` outside an `async` function (this includes the global scope).
