### ISSUE TITLE
Can't run start background actions

### ISSUE THREAD

**Issue by Thanhluc98** [Rapsssito/react-native-background-actions#75]
Hi guy!
I following your example code in this link "https://github.com/Rapsssito/react-native-background-actions/blob/master/examples/backgroundExample/App.js". But I can't run BackgroundJob.start(taskRandom, options);
The error is [TypeError: null is not an object (evaluating '_RNBackgroundActionsModule.RNBackgroundActions.start')].
Could you tell me how can I resolve this error?
Thank you!

**Comment by Rapsssito** [comment]
@Thanhluc98, are you using Expo?

**Comment by Rapsssito** [comment]
@Thanhluc98, you should also check if your issue can be fixed as stated in #21 or #34

**Comment by Thanhluc98** [comment]
@Rapsssito Thank you for your support!
I reinstalled the module, it worked for me.
Is it possible if I use this module run in background to connect BLE and save data to storage in both Android and iOS?

**Comment by Rapsssito** [comment]
@Thanhluc98, it might be possible, but I am not 100% sure. The only way to know is to test it.

**Comment by yoya93** [comment]
> @Rapsssito ¡ Gracias por tu apoyo!
> Reinstalé el módulo, funcionó para mí.
> ¿Es posible ejecutar este módulo en segundo plano para conectar BLE y guardar datos en el almacenamiento tanto en Android como en iOS?



> @Rapsssito Thank you for your support!
> I reinstalled the module, it worked for me.
> Is it possible if I use this module run in background to connect BLE and save data to storage in both Android and iOS?

Hello, I am at your same point. I am trying to use this module to detect beacons when the application is closed. Did it work for you? It would save me a lot of time. Thanks in advance
