### ISSUE TITLE
Cannot Execute Linking when app killed

### ISSUE THREAD

**Issue by subiyantoro** [Rapsssito/react-native-background-actions#77]
It's possible to execute Linking.openUrl() when app killed, i tried implement Linking.openUrl on my task but it's not working

`
```
const bgTask = async (task) => {
  const {delay} = task;
  await new Promise(async (resolve) => {
     endpoint.addListener('call_received', (newCall) => {
    const id = getNewUUID();
    const payload = {
      account: newCall,
      id: id,
    };
    store.dispatch(receivingCall(payload));
    Linking.openURL('vicall://call');
  });
  });
};
```

`

my redux dispatch it's working but Linking it's not

**Comment by Rapsssito** [comment]
@subiyantoro, I don't think you can use Linking while in the background. I am not sure, but since React Native goes into "paused" mode when the task has finished, Linking might not work.
