### ISSUE TITLE
Notification is not appearing in the status bar

### ISSUE THREAD

**Issue by sumanchem1989** [Rapsssito/react-native-background-actions#78]
Thank you very much for this package. I am using android and notification is not appearing in the status bar. Please tell me am I doing something wrong

**Comment by Rapsssito** [comment]
@sumanchem1989, I am sorry for your issue. Does the background task work?

**Comment by sumanchem1989** [comment]
Background task is working absolute fine but status bar notifications and also whenever I close the device the notification is not visible in the mobile screen before I opened my device. Notification is only visible whenever I slide it from the top.

**Comment by Rapsssito** [comment]
@sumanchem1989 I could not understand you. Does the notification appear in the notifications slider?
