### ISSUE TITLE
Background Location Tracking 

### ISSUE THREAD

**Issue by WaseemAhmed645** [Rapsssito/react-native-background-actions#79]
Is this possible to get the current updated location when application is in background state get every current position of user from google maps . i need this library for background tracking is this feasible for this task related to user location kindly reply

**Comment by Rapsssito** [comment]
@WaseemAhmed645 this library is for general use JavaScript code, for geolocation I recommend you using: https://github.com/react-native-geolocation/react-native-geolocation
