### ISSUE TITLE
[Question] Does this module work on iOS 13?

### ISSUE THREAD

**Issue by Saehanseul** [Rapsssito/react-native-background-actions#8]
I'm finding module which working at IOS 13.
I was used react-native-backgroun-timer. but it's not working at IOS 13.
I think it's because of new ios "background processing".

I wanna know about this module cover IOS 13.

**Comment by Rapsssito** [comment]
Sadly, this library **will not keep alive the app in the background by itself** on iOS. How I am working on an iOS 13 solutions using the new [`BGProcessingTaskRequest` API](BGProcessingTaskRequest).

However, you can rely on other libraries like `react-native-track-player` to keep your app alive in the background while you execute the JS from this library

I have updated the [library documentation about this subject](https://github.com/Rapsssito/react-native-background-actions#warning).

**Comment by robertfernanV** [comment]
@Rapsssito  Hi buddy, thanks for this great library! You comment about of  "react-native-track-player", but  i dont see any example with this two library  together.  do you have idea how implement? Thanks

**Comment by d0xi5** [comment]
You say in the main documentation on the warning part that the problem is that this library wont get the app to live forever in background.. But, will it live for at least 15-20 minutes? And, will this library allow to execute any JS code while on background as long as the app lives?

**Comment by Rapsssito** [comment]
@d0xi5, it might live for at least 5 minutes. However, **iOS can close it as soon as it wants**. It depends on your use case.

**Comment by zendevil** [comment]
Hi 
Is this issue being worked upon currently? Is there a solution for running background process in iOS reliably?

**Comment by Rapsssito** [comment]
@zendevil, I am sorry, but it is not possible. Take a look at my comment https://github.com/Rapsssito/react-native-background-actions/issues/8#issuecomment-575582339 for more info.

**Comment by Osric38** [comment]
Hi @Rapsssito , reading comment #8 you said to use "react-native-track-player" but it's for music play. Is there a way to keep working without using music player ? location only for example ?

My use case is "Tcp connection + Download files for 5 minutes". Then after 2/3 minutes I want to restart this process

**Comment by sreekanth-14** [comment]
> Hi @Rapsssito , reading comment #8 you said to use "react-native-track-player" but it's for music play. Is there a way to keep working without using music player ? location only for example ?
> 
> My use case is "Tcp connection + Download files for 5 minutes". Then after 2/3 minutes I want to restart this process

Hey I too have some similar use case

**Comment by sreekanth-14** [comment]
Actually I need a background process which looks out for data from a source for certain interval of time. That too I need specifically for iOS. Will try if I can use react-native-track-player for keeping the app alive

**Comment by Rapsssito** [comment]
@Osric38, check the [docs](https://github.com/Rapsssito/react-native-background-actions) for more info:

> However, you can rely on other libraries like react-native-track-player that use audio, geolocalization, etc

The issue here is that iOS does not allow your app to run in the background without a very specific reason. The main problem is with iOS itself and its restrictions on background tasks. Take a look at the [iOS docs](https://developer.apple.com/documentation/uikit/app_and_environment/scenes/preparing_your_ui_to_run_in_the_background) about this topic.

**Comment by Osric38** [comment]
@Rapsssito I know about this restriction, but with react-native-track-player, I will block user for reading his personnal musics, no ?

Have you already tried "react-native-background-geolocation" ?

In IOS 13, it seems background is allowed for some processing actions, have you tried this point ?

**Comment by Rapsssito** [comment]
@Osric38 I have not tested it with react-native-background-geolocation. Make sure to use react-native-track-player if the sound is a real part of the app, if it is not, your app will get rejected in the App Store.

Take into account that running the React Context is a relatively heavy processing action. However, I will take a look at the possibilities offered by iOS 13 as soon as possible.

**Comment by russmenum** [comment]
Did we ever get any progress on this?

Because I do not even think my  ``` const veryIntensiveTask = async (taskDataArguments) => { ``` is running on iOS. I basically need to do a GEO LOCATE and FETCH every so often even if the user is using another app like google maps.

I got one error POST to my BE and then when in iOS setting to tell it to just let the app always use location, but since never anything unless app is in the forground.

**Comment by Rapsssito** [comment]
@russmenum, for geolocation purposes, I highly recommend using just pure `react-native-background-geolocation`, `react-native-background-actions` works as a more general purpose background processing with limited functionality in iOS caused by iOS design.

**Comment by russmenum** [comment]
@Rapsssito , I am confused about how that is different? In looking at that it looks like all the calls run in the foreground so would not work while the app is not in the foreground? Maybe moot as after install trying to use it is crashing my app.

If it will work even when iOS app is in the background or another app is in use; great, but looks like all the doc is class bassed; would you know of any functional hook-based exsamples? I need hooks

**Comment by Ppang0405** [comment]
Please do something. Flutter has already had [flutter_workmanage](https://github.com/fluttercommunity/flutter_workmanager) that relied on Android's WorkManager, iOS' performFetchWithCompletionHandler and iOS BGAppRefreshTask. Could you do it in React Native?

**Comment by netqom** [comment]
s
