### ISSUE TITLE
I want to run two tasks, one after the other, but when I run the second, the first one runs too.

### ISSUE THREAD

**Issue by Arturo-J-Alva** [Rapsssito/react-native-background-actions#80]
When I stop the first task (with STOP) and execute the second, both are executed at the same time. I need is for them to run at different times.

--RUN TASK ONE (first moment)
await BackgroundService.start(veryIntensiveTaskONE, options)

--- STOP TASKS (second moment)
await BackgroundService.stop();

--RUN TASK TWO (third moment)
await BackgroundService.start(veryIntensiveTaskTWO, options)

*** Between the second moment and the third moment there is less than 1 second.

**Comment by Rapsssito** [comment]
@Arturo-J-Alva, calling `BackgroundService.stop();` while the app is in the foreground does not guarantee to stop your task immediately. The only way to **really** stop your task is to resolve the promise. For this purpose you could use `BackgroundService.isRunning()` to know if it has been stopped.

**Comment by Arturo-J-Alva** [comment]
I did what you told me, but it's the same as before. I observe is that the first task stays saved, and when I run another task, it runs together with the first one. 
Is there a method to delete the executed tasks? (after using the STOP method)

**Comment by Rapsssito** [comment]
@Arturo-J-Alva, if the first task **resolves** it should not continue running, it works as any other JS Promise. You might need to debug your code and make sure your first task resolves correctly **before** running your second task. Your code logic might be interfering with the promise resolution.

**Comment by sureshhallyali** [comment]
@Arturo-J-Alva its workied for me , if any other solution please let me know.

    `import BackgroundJob from 'react-native-background-actions';

    const sleep = (time) => new Promise((resolve) => setTimeout(() => resolve(), time));

    const taskRandomOne = async (taskData) => {

        await new Promise(async (resolve) => {

            // For loop with a delay
            const { delay } = taskData;
            console.log(BackgroundJob.isRunning(), delay)

            for (let i = 0; i<=5; i++) {
                console.log('Runned -> ', i);
                await BackgroundJob.updateNotification({ taskDesc: 'Runned -> ' + i });
                await sleep(delay);
            }
            
            // toggleBackground();
            console.log('SYNC Completed Work ! 1');
            await BackgroundJob.start(taskRandomTwo, optionsTwo);
            
            
        });
        return 25;
    };

    const taskRandomTwo = async (taskData) => {

        await new Promise(async (resolve) => {

            // For loop with a delay
            const { delay } = taskData;
            console.log(BackgroundJob.isRunning(), delay)

            for (let i = 0; i <10; i++) {
                console.log('Runned -> ', i);
                await BackgroundJob.updateNotification({ taskDesc: 'Runned -> ' + i });
                await sleep(delay);
            }
            toggleBackground();
            console.log('SYNC Completed Work ! 2');
        });
    };

    const optionsOne = {
        taskName: 'Registed',
        taskTitle: 'ExampleTask One',
        taskDesc: 'ExampleTask desc',
        taskIcon: {
            name: 'ic_launcher',
            type: 'mipmap',
        },
        color: '#ff00ff',
        linkingURI: 'exampleScheme://chat/jane',
        parameters: {
            delay: 1000,
        },
    };
    const optionsTwo = {
        taskName: 'Health Record',
        taskTitle: 'ExampleTask Two',
        taskDesc: 'ExampleTask desc',
        taskIcon: {
            name: 'ic_launcher',
            type: 'mipmap',
        },
        color: '#ff00ff',
        linkingURI: 'exampleScheme://chat/jane',
        parameters: {
            delay: 1000,
        },
    };

    function handleOpenURL(evt) {
        console.log(evt.url);
    }
    Linking.addEventListener('url', handleOpenURL);


    export const BackgroundJobRunning =async ()=>{

        playing = BackgroundJob.isRunning();

        console.log("playing", playing);

        toggleBackground = async () => {
        this.playing = !this.playing;
            if (this.playing) {
                try {
                    console.log('Trying to start background service');
                    await BackgroundJob.start(taskRandomOne, optionsOne)
                    
                    console.log('Successful start!');
                } catch (e) {
                    console.log('Error', e);
                }
            }
            else {
                
                await BackgroundJob.stop();
                console.log('Stop background service');
            }
        };

        toggleBackground()
    }`
