### ISSUE TITLE
State update showing Warning message  and not updating state while running background task and  I open app.

### ISSUE THREAD

**Issue by sureshhallyali** [Rapsssito/react-native-background-actions#85]
When I close and  open  app it's showing Warning  message for state update as shown below 

`ERROR  Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    in App (at renderApplication.js:47)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:107)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:134)
    in AppContainer (at renderApplication.js:40)
 LOG  Runned ->  11`

Code

        let [ counter, setCounter ] = useState( null );
        
        // state update function 
        const counterHandler=( i )=>{
             setCounter( i )
        }

        for (let i = 0; BackgroundJob.isRunning(); i++)  {
         
               // state update function calling to update state for every job running
                counterHandler( i );

                await BackgroundJob.updateNotification({ taskDesc: 'Runned -> ' + i });
                await sleep(delay);
         }

         await BackgroundJob.stop();

I need show background running process  on view  not on notification even I close app  and if I open app need show running  state process on View please is there any solution for that ?

Thank you in advance.

![Screenshot_2021-05-11-19-03-08-219_com rnfunctionality](https://user-images.githubusercontent.com/57383836/117826681-faa23780-b28d-11eb-92bf-03ab851be719.jpg)

**Comment by sureshhallyali** [comment]
Is there any update regarding this issue ??

**Comment by Rapsssito** [comment]
@sureshhallyali, please take a look at the [documentation](https://github.com/Rapsssito/react-native-background-actions/blob/master/USAGE.md):
```
// You can do anything in your task such as network requests, timers and so on,
// as long as it doesn't touch UI. Once your task completes (i.e. the promise is resolved),
// React Native will go into "paused" mode (unless there are other tasks running,
// or there is a foreground app).
```

You are receiving those errors because you are trying to update a React state object from the background. Your background tasks should not touch any UI components while the app is in the background.

**Comment by sureshhallyali** [comment]
@Rapsssito Thank you for the update but  is the  any way to show background running process in UI component

**Comment by Rapsssito** [comment]
@sureshhallyali, I highly recommend you checking out this issue: https://github.com/Rapsssito/react-native-background-actions/issues/57.
