### ISSUE TITLE
Gradle warning about use of `maven` plugin

### ISSUE THREAD

**Issue by ericleb010** [Rapsssito/react-native-background-actions#87]
When using `gradlew` version 6.8.1 to compile a project with `react-native-background-actions` (turning on all warnings), I get the following notice:

```
> Configure project :react-native-background-actions
The maven plugin has been deprecated. This is scheduled to be removed in Gradle 7.0. 
Please use the maven-publish plugin instead. Consult the upgrading guide for further information: 
https://docs.gradle.org/6.8.1/userguide/upgrading_version_5.html#legacy_publication_system_is_deprecated_and_replaced_with_the_publish_plugins
```

Sounds like this will break soon.

**Comment by Rapsssito** [comment]
@ericleb010, thanks for the notice! I will take it into consideration.

**Comment by Rapsssito** [comment]
@ericleb010, could you check if this issue has been solved with the last RN version (0.65)?

**Comment by nielson266** [comment]
Unfortunately not

**Comment by Rapsssito** [comment]
@ericleb010 and @nielson266, this issue should be fixed in the last version!
