### ISSUE TITLE
Task does not run in release mode

### ISSUE THREAD

**Issue by ammarahm-ed** [Rapsssito/react-native-background-actions#90]
Hey there! Great library. The task never fires in release mode however it works fine in debug? Here's my code:

```js

export const bgTaskOptions = {
  taskName: 'mySyncTask',
  taskTitle: 'Syncing',
  taskDesc: 'Syncing your notes.',
  taskIcon: {
    name: 'ic_stat_name',
    type: 'drawable',
  },
  color: '#ffffff',
};

const runBackgroundTask = () => {
  return new Promise(async (res, rej) => {
      console.log('init task')
      await BackgroundService.start(runTask, bgTaskOptions);
    });
}

const runTask = async () => {
// this code never runs in release, only debug.
  console.log('start task now')
  await BackgroundService.stop();
  console.log('done task now')
}
```
RN `v0.64` & hermes enabled.

**Comment by ammarahm-ed** [comment]
The issue was with the notification icon resource added only in debug mode. fixed

**Comment by ammarahm-ed** [comment]
> > The issue was with the notification icon resource added only in debug mode. fixed
> 
> how do you fixed it ?

Hey, so for me the case was that when I added the icons, they were only added to debug mode and not release. What i did was go to `android/app/debug/res` and move the drawable files from there to `android/app/main/res` folder.

**Comment by YashGupta61969** [comment]
> > > The issue was with the notification icon resource added only in debug mode. fixed
> > 
> > 
> > how do you fixed it ?
> 
> Hey, so for me the case was that when I added the icons, they were only added to debug mode and not release. What i did was go to `android/app/debug/res` and move the drawable files from there to `android/app/main/res` folder.

These changes were already available in my project. Still it fails the background task.
