### ISSUE TITLE
Geolocation ios

### ISSUE THREAD

**Issue by Anton-1408** [Rapsssito/react-native-background-actions#94]
Hello! I want to use react-native-background-actions with react-native-community/geolocation but app work on ios at background mode a 30s. DistanceFilter for geolocation - 1m

Code: 
 const veryIntensiveTask = async taskDataArguments => {
    await new Promise(async resolve => {
      try {
          watchLocation(async position => {
            dispatch(setCurrentLocation(position.coords));
          });
      } catch (error) {
        console.log(error);
      }
    });
  };

**Comment by Rapsssito** [comment]
@Anton-1408, you should take a look at the documentation for both libraries and ask a specific question. You might not need this library to accomplish your task.
