### ISSUE TITLE
Not working in iOS simulator

### ISSUE THREAD

**Issue by russmenum** [Rapsssito/react-native-background-actions#98]
This overall seems to be working well, but I am trying to debug iOS side now and it just seems to not work at all in the simulator. Is there some trick for iOS side simulator?

**Comment by russmenum** [comment]
Looks like it may not be working in the iPhone most of the time. I got one error on my test iPhone and have not been able to get any background process since

**Comment by Rapsssito** [comment]
@russmenum could you provide a reproducible code with your issue?

**Comment by hoseinfo** [comment]
same issue
does it wok on iOS devices?
